[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "in-reach"
version = "0.1.1"
description = "Python tooling and mini-IDE to help improve the Halo Reach scripting experience."
readme = "README.md"
requires-python = ">=3.14"
license = { file = "LICENSE" }
authors = [{ name = "Whiley True", email = "inreach.python@gmail.com" }]
dependencies = [
    "click==8.5.0",
    "python-dotenv==1.2.3",
    "tomlkit==0.15.1",
]

[project.optional-dependencies]
dev = ["pytest==8.4.2"]

[project.scripts]
in-reach = "in_reach.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
in_reach = [
    ".in-reach/example.env",
]