[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "inreach"
version = "0.1.4"
description = "Python tooling to help improve the Halo Reach scripting experience."
readme = "README.md"
requires-python = ">=3.14"
license = { file = "LICENSE" }
authors = [{ name = "Whiley True", email = "inreach.python@gmail.com" }]
dependencies = [
    "annotated-types==0.8.0",
    "click==8.4.2",
    "colorama==0.4.6",
    "iniconfig==2.3.0",
    "packaging==26.3",
    "pluggy==1.6.0",
    "pydantic==2.13.4",
    "pydantic_core==2.46.4",
    "Pygments==2.21.0",
    "pytest==9.1.1",
    "python-dotenv==1.2.3",
    "tomlkit==0.15.1",
    "typing-inspection==0.4.4",
    "typing_extensions==4.16.0",
]

[project.scripts]
inreach = "inreach.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
