""""Apply" -- compiles a project's hand-edited ``settings/*.json`` + ``edit/rvt/script.txt`` into a
real gametype ``.bin`` (PROMPT.md: the activity bar's "Apply" icon, "below the rvt icon"; later:
"applying changes should try and compile the jsons into a gametype and i[f] it fails then dont
allow application").

``settings/`` started life (see :mod:`in_reach.app.rvt.decompile`) as a live mirror of the source
``.bin``, kept in sync automatically whenever RVT saves over it -- but nothing stops a user from
hand-editing one of its JSON files directly in this IDE too, the same as any other text file. Apply
is how that edit actually takes effect: :func:`settings_have_unapplied_changes` is what the activity
bar's own Apply button enables/disables against (PROMPT.md: "this should only be available if a
user has made changes to files in settings"), and :func:`apply_settings_changes` is what clicking it
runs -- a thin wrapper around :func:`~in_reach.app.rvt.compile.run_compile`, which does the real
work (loads this project's own base ``.bin``, compiles ``edit/rvt/script.txt``, applies every
``settings/*.json`` onto the loaded variant, and -- only on success -- saves ``build/dist/*.bin``
and regenerates ``build/*.autogenerated.json`` from what actually got compiled). A failed compile
leaves ``build/`` completely untouched -- see that function's own docstring.
"""

from __future__ import annotations

import json
from pathlib import Path

from in_reach.app import new_project
from in_reach.app.rvt import decompile
from in_reach.app.rvt.compile import BuildResult, run_compile

#: (hand-editable settings/ filename, its build/*.autogenerated.json counterpart) -- used only by
#: settings_have_unapplied_changes()'s cheap "is there likely anything to apply" heuristic, not by
#: apply_settings_changes() itself any more (that's a real compile now, see module docstring).
_PAIRS = (
    (decompile.SETTINGS_FILENAME, decompile.GENERATED_SETTINGS_FILENAME),
    (decompile.SCRIPT_SETTINGS_FILENAME, decompile.GENERATED_SCRIPT_SETTINGS_FILENAME),
    (decompile.STRINGS_FILENAME, decompile.GENERATED_STRINGS_FILENAME),
)


def _normalized_json(path: Path) -> object:
    """``path``'s parsed content with ``$schema``/``_comment`` stripped -- ``settings/*.json``
    always embeds a ``$schema`` key (see :mod:`in_reach.app.rvt.schema_io`) that
    ``build/*.autogenerated.json`` deliberately never does (build/ is disposable output no editor
    tooling needs to validate against), so a *raw text* comparison between the two would always
    differ even right after a successful compile -- comparing parsed-and-stripped content instead
    is what actually answers "is there a real settings difference here." Returns ``None`` if
    ``path`` doesn't exist or isn't valid JSON, distinct from any real (dict/list) value."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if isinstance(data, dict):
        data.pop("$schema", None)
        data.pop("_comment", None)
    return data


def settings_have_unapplied_changes(folder: Path) -> bool:
    """Whether any of ``folder``'s ``settings/*.json`` files currently differ from their own
    ``build/*.autogenerated.json`` counterpart.

    Args:
        folder: A gametype project folder.

    Returns:
        ``True`` if any pair differs (including a ``settings/`` file whose ``build/`` counterpart
        doesn't exist at all yet) -- ``False`` if every pair matches, or ``settings/`` has nothing
        to compare in the first place (a project that's never been decompiled).
    """
    settings_dir = folder / new_project.SETTINGS_DIRNAME
    build_dir = folder / new_project.BUILD_DIRNAME
    for settings_name, generated_name in _PAIRS:
        settings_path = settings_dir / settings_name
        if not settings_path.is_file():
            continue
        generated_path = build_dir / generated_name
        if _normalized_json(settings_path) != _normalized_json(generated_path):
            return True
    return False


def apply_settings_changes(project_dir: Path, folder: Path) -> BuildResult:
    """Compiles ``folder``'s current ``settings/*.json`` + ``edit/rvt/script.txt`` into a real
    gametype ``.bin`` (PROMPT.md: "applying changes should try and compile the jsons into a
    gametype") -- see :func:`~in_reach.app.rvt.compile.run_compile` for exactly what that does.

    Args:
        project_dir: The active ``.in-reach`` folder, as returned by
            :func:`~in_reach.app.project.get_project_dir` -- needed to resolve this project's own
            ``init_gametype`` base ``.bin`` (see ``run_compile``'s own docstring).
        folder: A gametype project folder.

    Returns:
        A :class:`~in_reach.app.rvt.compile.BuildResult` -- ``success`` is ``False`` (with
        ``failure``/compiler messages populated, never raised) if compiling failed for any reason;
        the caller (``MainWindow.apply_settings_changes()``) is what decides how to surface that
        (PROMPT.md: "raise errors in text window") and blocks ``build/`` from changing when it
        does, simply by virtue of ``run_compile`` never having written anything on a failure.
    """
    return run_compile(project_dir, folder, save=True)
