""""Apply" -- compiles a project's hand-edited ``settings/*.json`` + ``script/output.txt`` into a
real gametype ``.bin`` (PROMPT.md: the activity bar's "Apply" icon, "below the rvt icon"; later:
"applying changes should try and compile the jsons into a gametype and i[f] it fails then dont
allow application").

``settings/`` started life (see :mod:`in_reach.app.rvt.decompile`) as a live mirror of the source
``.bin``, kept in sync automatically whenever RVT saves over it -- but nothing stops a user from
hand-editing one of its JSON files directly in this IDE too, the same as any other text file. Apply
is how that edit actually takes effect: :func:`settings_have_unapplied_changes` is what the activity
bar's own Apply button enables/disables against (PROMPT.md: "this should only be available if a
user has made changes to files in settings"), and :func:`apply_settings_changes` is what clicking it
runs -- a thin wrapper around :func:`~in_reach.app.rvt.compile.run_compile`, which does the real
work (loads this project's own base ``.bin``, compiles ``script/output.txt``, applies every
``settings/*.json`` onto the loaded variant, and -- only on success -- saves ``build/dist/*.bin``
and regenerates ``build/*.autogenerated.json`` from what actually got compiled). A failed compile
leaves ``build/`` completely untouched -- see that function's own docstring.
"""

from __future__ import annotations

import json
from pathlib import Path

from in_reach.app import new_project
from in_reach.app.rvt import decompile
from in_reach.app.rvt.compile import BuildResult, run_compile
from in_reach.app.rvt.strings_io import LANGUAGES as _LANGUAGE_CODES

_LANGUAGE_CODE_SET = frozenset(_LANGUAGE_CODES)

#: (hand-editable settings/ filename, its build/*.autogenerated.json counterpart) -- used only by
#: settings_have_unapplied_changes()'s cheap "is there likely anything to apply" heuristic, not by
#: apply_settings_changes() itself any more (that's a real compile now, see module docstring).
_PAIRS = (
    (decompile.SETTINGS_FILENAME, decompile.GENERATED_SETTINGS_FILENAME),
    (decompile.SCRIPT_SETTINGS_FILENAME, decompile.GENERATED_SCRIPT_SETTINGS_FILENAME),
    (decompile.STRINGS_FILENAME, decompile.GENERATED_STRINGS_FILENAME),
)


#: How many decimal places a float is rounded to before comparing (PROMPT.md: "we're having to
#: double click apply for apply to work") -- ``game_settings.title_update_settings``'s handful of
#: 0.0-2.0-fraction fields go through a real fixed-point *.bin* encoding on every compile (the same
#: quantization ``tests/app/rvt/test_compile.py``'s own round-trip test tolerates with
#: ``pytest.approx(..., abs=0.001)``), so ``settings/settings.json``'s exact hand-typed value (say
#: ``0.5``) can never equal build's freshly re-extracted one (``0.4999999888241291``) even
#: immediately after a fully successful Apply -- exact float equality treated that as "still
#: unapplied" forever, no matter how many more times Apply was clicked.
_FLOAT_COMPARISON_PRECISION = 3


#: ``settings/strings.json``'s own ``StringTableEntry``/``TeamNameEntry`` shape (see
#: :mod:`in_reach.app.rvt.models.strings`) is ``{"index": int, "text" | "name": LocalizedText}`` --
#: this pair of key names is what :func:`_normalize_for_comparison` uses to recognize a
#: ``LocalizedText`` value worth :func:`_normalize_localized_text`-ing, since a bare string or dict
#: value alone carries no shape information of its own to key off.
_LOCALIZED_TEXT_KEYS = ("text", "name")


def _normalize_localized_text(value: dict | str | None) -> dict[str, str]:
    """Normalizes one ``LocalizedText`` value -- ``None``, a bare string (shorthand for
    ``{"english": value}``, see ``models/strings.py``'s own docstring), or a partial dict -- to a
    full per-language dict with every language present, every omitted or ``None`` one filled in
    with ``""``. That's what a freshly-*compiled* entry always reads back as once any language on
    it has real content (a newly-created native string-table entry has no way to leave an
    individual language slot truly unset -- see :mod:`in_reach.app.rvt.strings_writer`'s own module
    docstring for the ``None``-vs-``""`` distinction this collapses), where hand-edited input
    commonly only ever provides English at all (the normal, expected way to type a team/string
    name) -- without this, editing one hits :func:`settings_have_unapplied_changes`'s "stuck
    reading as unapplied no matter how many more times Apply is clicked" bug on literally every
    such field (PROMPT.md: "we're having to double click apply for apply to work")."""
    if value is None:
        value = {}
    elif isinstance(value, str):
        value = {"english": value}
    return {language: (value.get(language) or "") for language in _LANGUAGE_CODE_SET}


def _normalize_for_comparison(value):
    """Recursively normalizes a parsed JSON value so :func:`settings_have_unapplied_changes`'s
    comparison tolerates harmless round-trip differences a real compile introduces (PROMPT.md:
    "we're having to double click apply for apply to work" -- each one otherwise leaves the Apply
    button stuck permanently "enabled" after an otherwise fully successful Apply, however many more
    times it's clicked, since neither ever resolves by re-comparing the exact same two values):

    - A float rounded to :data:`_FLOAT_COMPARISON_PRECISION` places -- see that constant's own
      docstring.
    - Any ``"text"``/``"name"`` value on a dict that also has an ``"index"`` key (a
      ``StringTableEntry``/``TeamNameEntry`` -- see :data:`_LOCALIZED_TEXT_KEYS`) run through
      :func:`_normalize_localized_text`.
    - ``None`` treated as equal to ``""`` everywhere else.
    """
    if value is None:
        return ""
    if isinstance(value, float):
        return round(value, _FLOAT_COMPARISON_PRECISION)
    if isinstance(value, dict):
        is_string_table_entry = "index" in value
        normalized = {}
        for key, entry_value in value.items():
            if is_string_table_entry and key in _LOCALIZED_TEXT_KEYS:
                normalized[key] = _normalize_localized_text(entry_value)
            else:
                normalized[key] = _normalize_for_comparison(entry_value)
        return normalized
    if isinstance(value, list):
        return [_normalize_for_comparison(v) for v in value]
    return value


def _normalized_json(path: Path) -> object:
    """``path``'s parsed content with ``$schema``/``_comment``/``meta.generated_at`` stripped, and
    the rest passed through :func:`_normalize_for_comparison` -- ``settings/*.json`` always embeds
    a ``$schema`` key (see :mod:`in_reach.app.rvt.schema_io`) that ``build/*.autogenerated.json``
    deliberately never does (build/ is disposable output no editor tooling needs to validate
    against), so a *raw text* comparison between the two would always differ even right after a
    successful compile -- comparing parsed-and-stripped content instead is what actually answers
    "is there a real settings difference here."

    ``meta.generated_at`` needs the same treatment for a subtler reason: it's stamped fresh with
    ``datetime.now()`` on *every* extraction (see :func:`~in_reach.app.rvt.extraction._extract_meta`),
    not carried over from the source ``.bin``, so ``settings/settings.json``'s own timestamp (from
    whenever it was first decompiled) can never equal a freshly-written build snapshot's -- without
    stripping it here, this always read as "unapplied changes" even immediately after a fully
    successful Apply, which is the bug this fixes (the Apply button never got its own "no entry"
    badge back once it had ever been enabled once).

    ``multiplayer.game_settings.team_settings.teams[].name`` is stripped for a related reason: per
    :func:`~in_reach.app.rvt.settings_writer._apply_team_entry`'s own docstring, this field is
    *never* applied on compile at all -- a team's real name goes through ``strings_writer``'s own
    ``apply_strings()``/``_apply_team_names()`` instead (``settings/strings.json``'s own
    ``teams[].name``), so this copy is decompile-only display data, last refreshed whenever
    ``settings/`` was decompiled/resynced -- not by Apply, which never writes back into
    ``settings/``. Renaming a team via ``strings.json`` (the normal way) leaves this stale forever
    after, otherwise -- the same "stuck reading as unapplied no matter how many more times Apply is
    clicked" bug as the other two normalizations above.

    ``script_settings.json``'s own ``forge_labels[].name`` / ``scripted_options[].name``/``desc``
    (and each of ``values``/``range_default``/``range_min``/``range_max``) / ``scripted_player_
    traits[].name``/``desc`` are stripped for the identical reason -- see
    :func:`_strip_never_applied_script_settings_text`.

    ``multiplayer.game_settings.metadata.description_string`` is stripped for a related-but-subtler
    reason: per ``compile.py``'s own ``run_compile()`` comment ("Order matters: ... strings applies
    last so settings/strings.json's own multi-language text wins over settings.json's single-
    language description_string"), ``strings.json``'s ``meta.description`` is *always* applied after
    ``description_string``, unconditionally overwriting it -- so editing ``description_string`` via
    ``settings.json`` directly can never itself take effect (only editing ``strings.json``'s own
    ``meta.description[0]`` does), leaving settings.json's copy permanently stale relative to
    build's snapshot the moment it's edited that way, the same as the fields above.

    Returns ``None`` if ``path`` doesn't exist or isn't valid JSON, distinct from any real
    (dict/list) value.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if isinstance(data, dict):
        data.pop("$schema", None)
        data.pop("_comment", None)
        meta = data.get("meta")
        if isinstance(meta, dict):
            meta.pop("generated_at", None)
        _strip_never_applied_multiplayer_mirrors(data)
        _strip_never_applied_script_settings_text(data)
    return _normalize_for_comparison(data)


def _strip_never_applied_multiplayer_mirrors(data: dict) -> None:
    try:
        teams = data["multiplayer"]["game_settings"]["team_settings"]["teams"]
    except (KeyError, TypeError):
        pass
    else:
        if isinstance(teams, list):
            for team in teams:
                if isinstance(team, dict):
                    team.pop("name", None)

    try:
        metadata = data["multiplayer"]["game_settings"]["metadata"]
    except (KeyError, TypeError):
        return
    if isinstance(metadata, dict):
        metadata.pop("description_string", None)


def _strip_never_applied_script_settings_text(data: dict) -> None:
    """``script_settings.json``'s own ``ForgeLabel.name``/``required_object_type_name``/
    ``required_team_name`` / ``ScriptedOption[Value].name``/``desc`` / ``ScriptedPlayerTraits.
    name``/``desc`` / ``ScriptedStat.name`` / ``RequiredObjectTypes.object_type_names`` are, per
    ``settings_writer.py``'s own module docstring ("Text fields ... are deliberately NOT applied by
    this module at all") and its own ``_apply_forge_label()``/``_apply_required_object_types()``
    docstrings/bodies, never written back on compile -- they're resolved lookups (into the
    ``script_strings`` table, or via ``rvt.object_type_name()``/the map's own configured team list,
    see ``extraction.py``'s ``_text_or_empty()``/``_object_type_name()``/
    ``_resolve_const_team_name()``) computed fresh only at *extraction* time, not something this
    file's own compile step ever touches. Editing whatever each one is actually resolved *from* --
    the real string-table entry (via ``strings.json``), a forge label's ``required_object_type``/
    ``required_team`` raw index/enum, or ``required_object_types.object_type_indices`` -- leaves
    these decompile-only mirrors in ``settings/script_settings.json`` stale forever after, the
    exact same "stuck reading as unapplied no matter how many more times Apply is clicked" bug as
    :func:`_strip_never_applied_multiplayer_mirrors` fixes for team names (PROMPT.md: "we're having to
    double click apply for apply to work")."""
    forge_labels = data.get("forge_labels")
    if isinstance(forge_labels, list):
        for label in forge_labels:
            if isinstance(label, dict):
                label.pop("name", None)
                label.pop("required_object_type_name", None)
                label.pop("required_team_name", None)

    scripted_options = data.get("scripted_options")
    if isinstance(scripted_options, list):
        for option in scripted_options:
            if not isinstance(option, dict):
                continue
            option.pop("name", None)
            option.pop("desc", None)
            values = option.get("values")
            if isinstance(values, list):
                for value in values:
                    if isinstance(value, dict):
                        value.pop("name", None)
                        value.pop("desc", None)
            for key in ("range_default", "range_min", "range_max"):
                value = option.get(key)
                if isinstance(value, dict):
                    value.pop("name", None)
                    value.pop("desc", None)

    scripted_player_traits = data.get("scripted_player_traits")
    if isinstance(scripted_player_traits, list):
        for trait in scripted_player_traits:
            if isinstance(trait, dict):
                trait.pop("name", None)
                trait.pop("desc", None)

    scripted_stats = data.get("scripted_stats")
    if isinstance(scripted_stats, list):
        for stat in scripted_stats:
            if isinstance(stat, dict):
                stat.pop("name", None)

    required_object_types = data.get("required_object_types")
    if isinstance(required_object_types, dict):
        required_object_types.pop("object_type_names", None)


def settings_have_unapplied_changes(folder: Path) -> bool:
    """Whether any of ``folder``'s ``settings/*.json`` files currently differ from their own
    ``build/*.autogenerated.json`` counterpart.

    Args:
        folder: A gametype project folder.

    Returns:
        ``True`` if any pair differs (including a ``settings/`` file whose ``build/`` counterpart
        doesn't exist at all yet) -- ``False`` if every pair matches, or ``settings/`` has nothing
        to compare in the first place (a project that's never been decompiled).
    """
    settings_dir = folder / new_project.SETTINGS_DIRNAME
    build_dir = folder / new_project.BUILD_DIRNAME
    for settings_name, generated_name in _PAIRS:
        settings_path = settings_dir / settings_name
        if not settings_path.is_file():
            continue
        generated_path = build_dir / generated_name
        if _normalized_json(settings_path) != _normalized_json(generated_path):
            return True
    return False


def apply_settings_changes(project_dir: Path, folder: Path) -> BuildResult:
    """Compiles ``folder``'s current ``settings/*.json`` + ``script/output.txt`` into a real
    gametype ``.bin`` (PROMPT.md: "applying changes should try and compile the jsons into a
    gametype") -- see :func:`~in_reach.app.rvt.compile.run_compile` for exactly what that does.

    Args:
        project_dir: The active ``.in-reach`` folder, as returned by
            :func:`~in_reach.app.project.get_project_dir` -- needed to resolve this project's own
            ``init_gametype`` base ``.bin`` (see ``run_compile``'s own docstring).
        folder: A gametype project folder.

    Returns:
        A :class:`~in_reach.app.rvt.compile.BuildResult` -- ``success`` is ``False`` (with
        ``failure``/compiler messages populated, never raised) if compiling failed for any reason;
        the caller (``MainWindow.apply_settings_changes()``) is what decides how to surface that
        (PROMPT.md: "raise errors in text window") and blocks ``build/`` from changing when it
        does, simply by virtue of ``run_compile`` never having written anything on a failure.
    """
    return run_compile(project_dir, folder, save=True)
