"""Scaffolds a new gametype project folder -- the Welcome tab's "Start" actions.

The project folder is named after a short generated id, not the title (PROMPT.md) -- titles are
free text now (any characters, since nothing needs to be a legal Windows name once it's no longer
also a folder name), read back from ``settings/settings.json``'s own ``meta.title`` instead (there
used to be a per-project ``README.md`` carrying a copy of it for display, removed per PROMPT.md:
"please remove the README.md file completely" -- ``settings.json`` was always the authoritative
copy anyway, see :func:`read_project_title`). A README.md has since come back as a plain,
title-free stub (PROMPT.md: "please also add a second stubbed README.md file in the generated
project folder") -- it carries no project data of its own to keep in sync, so none of the earlier
reasoning for removing it applies. Everything else about the shape is carried over from
the v2 prototype's ``inreach init``, restructured per several PROMPT.md passes into:

- ``script/output.txt`` -- the one genuinely hand-editable thing: the Megalo script, decompiled once
  as a starting point, then never auto-touched again.
- ``settings/`` -- a live, always-in-sync mirror of the source ``.bin``'s own settings (edited
  through RVT's own GUI, not by hand here) -- ``settings.json``/``script_settings.json``/
  ``strings.json``.
- ``schemas/`` -- the JSON Schema files those three validate against (PROMPT.md: "move
  settings/schemas into schemas" -- a project-root folder of their own, not nested under
  ``settings/``), regenerated fresh on every decompile/resync.
- ``build/`` -- disposable, gitignored output: the same data as ``settings/`` again, as a
  point-in-time ``*.autogenerated.json`` snapshot, plus ``valid_maps.json`` (the shared
  ``.in-reach/maps.json`` scan, narrowed down to what this gametype can actually be played on -- see
  :func:`~in_reach.app.maps_io.filter_maps_for_gametype`; PROMPT.md: "move settings/valid_maps.json
  to build/valid_maps.json") and, once compiling exists, the actual compiled ``.bin``/``.mglo``
  under ``build/dist/``.

A ``source_variant`` is decompiled straight into both ``settings/`` and ``build/`` at creation
(PROMPT.md: "when a project is selected the gametype is decompiled as in the previous repos"), via
:mod:`in_reach.app.rvt.decompile` -- non-fatally, see :func:`_decompile_source_variant` -- which is
also where this project's own category/category_icon end up, stamped into the decompiled
``settings.json`` itself (PROMPT.md: "we can get rid of user_settings.json ad move category and
category_icon into settings.json" -- there's no separate ``user_settings.json`` file at all).
``settings/`` and ``build/`` are kept in sync with the ``.bin`` afterward too, whenever RVT saves
over it (see ``MainWindow``'s own ``.bin``-file-watcher) -- only ``script/output.txt`` is ever left
alone once written.
"""

from __future__ import annotations

import json
import secrets
import shutil
import string
from pathlib import Path

from in_reach.app import env_file, maps_io
from in_reach.app.categories import EngineCategory, EngineIcon, default_icon_for, mismatch_warning

PROJECT_DIR_KEY = "PROJECT_DIR"

#: PROMPT.md: "rename edit to script: and then move script.txt to be script/game.txt" (later
#: renamed again, PROMPT.md: "please rename game.txt to output.txt" -- see
#: :data:`~in_reach.app.rvt.decompile.SCRIPT_FILENAME`) -- the one genuinely hand-editable thing in
#: a project, a flat folder now rather than nested under a no-longer-meaningful "rvt" subdirectory.
SCRIPT_DIRNAME = "script"
SETTINGS_DIRNAME = "settings"
#: PROMPT.md: "move settings/schemas into schemas" -- a project-root folder of its own, not nested
#: under SETTINGS_DIRNAME (see :mod:`in_reach.app.rvt.decompile`, which writes into it).
SCHEMA_DIRNAME = "schemas"
BUILD_DIRNAME = "build"
BUILD_DIST_SUBDIR = "dist"
INIT_GAMETYPE_DIRNAME = "init_gametype"
#: PROMPT.md: "please also add a Notes.txt (with first line Use this space for free form notes)".
NOTES_FILENAME = "Notes.txt"
_NOTES_TEMPLATE = "Use this space for free form notes.\n"
#: PROMPT.md: "please also add a second stubbed README.md file in the generated project folder"
#: -- distinct from (and, unlike the old one this module's docstring mentions removing, carries no
#: copy of) the title: a plain stub, same treatment as the .in-reach-level one (see
#: :func:`~in_reach.app.project.ensure_readme`).
README_FILENAME = "README.md"
_README_TEMPLATE = "# Gametype Project\n\nStub README -- more to come.\n"

MAX_TITLE_LENGTH = 32
MAX_DESCRIPTION_LENGTH = 137

#: How many collision retries :func:`_generate_project_id` allows before giving up -- a collision
#: at :data:`PROJECT_ID_LENGTH` characters of real randomness is practically impossible; this loop
#: exists purely so a freak one fails into "try another id" rather than
#: :func:`create_gametype_project` raising :class:`FileExistsError` for a reason that has nothing
#: to do with the caller's own title.
_MAX_ID_ATTEMPTS = 20

#: How many characters :func:`_random_token` draws from :data:`_PROJECT_ID_ALPHABET` -- see
#: :func:`_generate_project_id`'s own docstring for why plain alphanumeric rather than base64url.
PROJECT_ID_LENGTH = 8

#: PROMPT.md: "please dont have hyphens in uuids for file names" -- plain alphanumeric only, no
#: ``-``/``_`` separator characters that a base64url alphabet would otherwise include (see
#: :func:`_generate_project_id`'s own docstring).
_PROJECT_ID_ALPHABET = string.ascii_letters + string.digits

_ENV_NAME = ".env"
_VARIANT_SUFFIX = ".bin"

# build/ is rebuildable on demand from edit/, so it's ignored via its own self-contained
# .gitignore rather than an entry in the user's repo-level one.
_BUILD_GITIGNORE = "*\n!.gitignore\n"



def is_valid_title(title: str) -> bool:
    """Reports whether ``title`` is usable as this project's title.

    No longer a folder-name check (PROMPT.md: the project folder is a generated id, not the
    title -- see :func:`create_gametype_project`) -- title can be any text now, the same rule
    :data:`MAX_DESCRIPTION_LENGTH`'s description field already followed.

    Args:
        title: The candidate project title.

    Returns:
        Whether ``title``, stripped, is non-empty and at most :data:`MAX_TITLE_LENGTH` characters.
    """
    return bool(title.strip()) and len(title) <= MAX_TITLE_LENGTH


def list_variants(folder: Path) -> list[tuple[str, Path]]:
    """Lists the game variants in ``folder``, as ``(name, path)`` pairs sorted by name.

    Named by filename, not by the variant's own in-game title: reading that back out means loading
    the ``.bin`` through the ReachVariantTool extension, which isn't ported into this repo yet
    (v2's ``app/rvt/browse.py`` did exactly that). Reach names the file after the gametype anyway,
    so the two normally agree for anything the user saved themselves.

    Args:
        folder: A game-variants folder -- one of the standard/hopper/personal locations resolved by
            :mod:`in_reach.app.system_verify`.

    Returns:
        Every ``.bin`` directly inside ``folder``. Empty if it doesn't exist or holds none.
    """
    if not folder.is_dir():
        return []
    return sorted(
        ((path.stem, path) for path in folder.glob(f"*{_VARIANT_SUFFIX}") if path.is_file()),
        key=lambda pair: pair[0].lower(),
    )


def source_variant_path(project_dir: Path, gametype_folder: Path) -> Path:
    """The ``.bin`` a gametype project was created from (and decompiled from -- see
    :mod:`in_reach.app.rvt.decompile`), at ``.in-reach/init_gametype/<id>.bin``. A frozen snapshot
    of whatever the project started from -- never touched again after creation (see
    :func:`~in_reach.app.rvt.compile.run_compile`'s own docstring for why a compile always rebuilds
    from this exact fixed base rather than incrementally re-using ``build/``'s own prior output).

    Not what :meth:`in_reach.ide.main_window.MainWindow.launch_rvt` opens RVT against -- that's
    :func:`compiled_variant_path`, the freshly-*built* gametype (this project's own hand-edited
    settings/script actually baked in), not this untouched original.

    Args:
        project_dir: The project's ``.in-reach`` folder.
        gametype_folder: The gametype project's own folder, as returned by
            :func:`create_gametype_project` -- only its ``name`` (the generated id) is used.

    Returns:
        The expected path, whether or not a file actually exists there yet.
    """
    return project_dir / INIT_GAMETYPE_DIRNAME / f"{gametype_folder.name}{_VARIANT_SUFFIX}"


def compiled_variant_path(folder: Path) -> Path:
    """Where a successful compile (the activity bar's "Apply", or a ``launch_rvt()`` doing the same
    thing first -- see that method's own docstring) saves ``folder``'s own freshly-built gametype:
    ``build/dist/<folder.name>.bin``.

    PROMPT.md: "when clicking into rvt, it seems to be showing blank gametype and description not
    the contents from the saved settings" -- :meth:`~in_reach.ide.main_window.MainWindow.launch_rvt`
    used to hand RVT :func:`source_variant_path` instead (the project's original, never-touched
    starting point, per its own docstring), so RVT always opened onto whatever the source ``.bin``
    happened to look like at creation time, never anything the user had actually saved into
    ``settings/`` since. This is the file that actually reflects that.

    Args:
        folder: The gametype project folder, as returned by :func:`create_gametype_project`.

    Returns:
        The expected path, whether or not a file actually exists there yet -- callers should still
        check :meth:`Path.is_file`, since nothing's been compiled there until a compile actually
        succeeds at least once.
    """
    return folder / BUILD_DIRNAME / BUILD_DIST_SUBDIR / f"{folder.name}{_VARIANT_SUFFIX}"


_GENERATED_SUFFIX = ".autogenerated.json"


_SCHEMA_SUFFIX = ".schema.json"


def is_generated_file(path: Path) -> bool:
    """Whether ``path`` is one of a project's own generated outputs -- ``build/``'s compiled
    ``.bin``/``.mglo`` and its ``*.autogenerated.json`` re-extraction snapshots (PROMPT.md), plus
    ``schemas/*.schema.json`` -- never meant to be hand-edited, since the next successful
    build/resync/decompile overwrites it wholesale (schema files: "regenerated fresh whenever a
    project is (re)decompiled", see :mod:`in_reach.app.rvt.schema_io`). PROMPT.md: "schema files
    should be non-editable (by hand)". The IDE opens one read-only rather than letting an edit
    silently vanish on the next one (see :meth:`in_reach.ide.tabs.TabPane.open_file`).

    Args:
        path: Any file path -- doesn't have to point inside a real project, or even exist.

    Returns:
        Whether ``path`` sits inside a ``build/`` folder at any depth, its own name ends with
        ``.autogenerated.json`` (a belt-and-braces check -- every such file already lives under
        ``build/`` today, but the name alone is just as unambiguous a signal on its own), or its
        own name ends with ``.schema.json``.
    """
    return (
        BUILD_DIRNAME in path.parts
        or path.name.endswith(_GENERATED_SUFFIX)
        or path.name.endswith(_SCHEMA_SUFFIX)
    )


def read_project_title(folder: Path) -> str:
    """Reads a project folder's title back out of its own ``settings/settings.json`` ``meta.title``
    (PROMPT.md: "please remove the README.md file completely" -- that used to carry a separate
    display copy of the title; ``settings.json`` was always the authoritative one, stamped there at
    creation and kept current by every later decompile/resync/Apply, see
    :mod:`in_reach.app.rvt.decompile`'s own module docstring).

    The folder itself is named after a generated id (see :func:`create_gametype_project`), not the
    title, so anything wanting to show a project by name -- the Explorer's own project tabs, the
    Welcome tab's Recent list, the File menu's Open Recent, an open editor's breadcrumb -- reads it
    back from here rather than the folder name.

    Args:
        folder: A gametype project folder.

    Returns:
        ``settings.json``'s own ``meta.title``, or ``folder.name`` if there's no ``settings.json``
        yet (a genuinely blank project -- see :func:`create_gametype_project`'s own docstring) or
        it fails to parse, or its title is blank -- the id is still a usable, if uglier, fallback
        label.
    """
    settings_path = folder / SETTINGS_DIRNAME / "settings.json"
    try:
        data = json.loads(settings_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return folder.name
    title = (data.get("meta") or {}).get("title")
    return title or folder.name


def _decompile_source_variant(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory,
    category_icon: EngineIcon,
    map_entries: list[maps_io.MapEntry],
    title: str = "",
    description: str = "",
) -> str | None:
    """Decompiles ``bin_path`` into ``folder``'s ``settings/``/``build/`` (PROMPT.md: "when a
    project is selected the gametype is decompiled as in the previous repos"), stamping this
    project's own category/category_icon/title/description into the resulting ``settings.json``
    (PROMPT.md: "move category and category_icon into settings.json"; "when setting a title and
    description, this is not being set in settings.json") and ``valid_maps.json`` narrowed down
    from ``map_entries`` (PROMPT.md: "inside settings/maps we should [have] valid_maps.json instead
    ... this should only fill with maps that are valid for this gametype") -- imported lazily so
    that creating a blank project (no ``source_variant``) never pays for importing pydantic/the
    native RVT extension at all.

    Non-fatal by design: a ``.bin`` the native extension can't load or make sense of shouldn't
    block the project from being created at all -- ``settings/``/``build/`` are just left as they
    started (empty), same as before this was wired up, and the caller surfaces the returned message
    the same way it already surfaces a category/icon mismatch warning.

    Returns:
        ``None`` on success, else a user-facing message describing what went wrong.
    """
    from in_reach.app.rvt.decompile import decompile_into_project

    try:
        decompile_into_project(
            bin_path,
            folder,
            category=category,
            category_icon=category_icon,
            map_entries=map_entries,
            title=title,
            description=description,
        )
    except Exception as exc:  # noqa: BLE001 -- native/pydantic code can raise almost anything
        return f"Couldn't decompile {bin_path.name} into this project:\n{exc}"
    return None


def _random_token() -> str:
    """:data:`PROJECT_ID_LENGTH` characters drawn from :data:`_PROJECT_ID_ALPHABET`. Its own
    function purely as a test seam (same reasoning as e.g. ``MainWindow.ask_open_folder``), so
    :func:`_generate_project_id`'s collision-retry tests can monkeypatch a fixed sequence of
    candidates without needing them to actually be :data:`PROJECT_ID_LENGTH` characters long."""
    return "".join(secrets.choice(_PROJECT_ID_ALPHABET) for _ in range(PROJECT_ID_LENGTH))


def _generate_project_id(root: Path) -> str:
    """A short, random id that doesn't already name a folder under ``root`` -- 8 plain
    alphanumeric characters (PROMPT.md: "can it be a short uuid").

    A full, un-truncated uuid4 was tried first (per an earlier PROMPT.md pass: "please use a uuid
    that is just a different uuid scheme the[n] used by dulwich" -- this repo is getting its own
    embedded VCS (Dulwich), whose own object ids are 40-character SHA-1 hex digests with no
    separators, so a folder name must never be mistakable for one of those), but that read as too
    long for everyday use. Shortening it back down to a hex fragment would have reintroduced the
    exact problem an earlier PROMPT.md pass already flagged once (a short hex id reads too much
    like a truncated git hash -- the reason a brief random-animal-name scheme existed in between).
    ``secrets.token_urlsafe`` was tried next -- short, and its base64url alphabet makes an
    all-hex-digit result astronomically unlikely, so it can't be mistaken for a hash of any
    length, truncated or not -- but that alphabet (``A-Za-z0-9-_``) can itself render with a
    leading/embedded ``-``, which a later PROMPT.md pass flagged as an unwanted character in a
    file/folder name: "please dont have hyphens in uuids for file names". Drawing straight from
    :data:`_PROJECT_ID_ALPHABET` (plain letters and digits, via :func:`_random_token`) sidesteps
    that too, at the same length and comparable entropy (62 possibilities per character vs.
    base64url's 64).

    Args:
        root: The folder new project folders are created directly under.

    Returns:
        A :data:`PROJECT_ID_LENGTH`-character alphanumeric token not already used as a folder name
        under ``root``.

    Raises:
        FileExistsError: In the practically-impossible case that :data:`_MAX_ID_ATTEMPTS`
            freshly-generated tokens in a row all collide with an existing folder under ``root``.
    """
    for _ in range(_MAX_ID_ATTEMPTS):
        candidate = _random_token()
        if not (root / candidate).exists():
            return candidate
    raise FileExistsError(f"Could not find a free project id under {root} after {_MAX_ID_ATTEMPTS} attempts.")


def create_gametype_project(
    project_dir: Path,
    title: str,
    description: str = "",
    source_variant: Path | None = None,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    personal_maps_dir: Path | None = None,
    standard_maps_dir: Path | None = None,
    hopper_maps_dir: Path | None = None,
) -> tuple[Path, str | None]:
    """Creates ``<root>/<id>/`` and everything a new gametype project starts with.

    Args:
        project_dir: The project's ``.in-reach`` folder. The new gametype folder is created
            alongside it, under the same root, and ``PROJECT_DIR`` in its ``.env`` is pointed at
            the result.
        title: The project title, already validated by :func:`is_valid_title`. No longer names the
            folder -- stamped into ``settings/settings.json``'s own ``meta.title`` instead (via
            decompile, below), which :func:`read_project_title` reads back.
        description: Optional description, stamped into ``settings.json``'s ``meta.description``
            the same way.
        source_variant: A ``.bin`` to start from, copied to
            ``.in-reach/init_gametype/<id>.bin`` and decompiled from there into ``settings/`` and
            ``build/`` (see :func:`_decompile_source_variant`). ``None`` starts a genuinely blank
            project -- no
            ``.bin`` at all, so nothing to decompile -- though in practice every UI-driven flow
            (including "New Blank Project") always passes one now, resolving to one of this
            package's own bundled templates (see :mod:`in_reach.app.blank_variant`) when the user
            didn't start from a real built-in/personal variant.
        category: This project's :class:`~in_reach.app.categories.EngineCategory`. Defaults to
            :attr:`~in_reach.app.categories.EngineCategory.none` (Forge/no category).
        category_icon: This project's :class:`~in_reach.app.categories.EngineIcon`. Defaults to
            whichever icon corresponds to ``category`` (see
            :func:`~in_reach.app.categories.default_icon_for`) -- explicitly pass a different one
            to knowingly mismatch them.
        personal_maps_dir: The resolved personal map-variants folder, if any -- scanned into
            ``.in-reach/maps.json``.
        standard_maps_dir: The resolved standard map-variants folder, if any.
        hopper_maps_dir: The resolved hopper map-variants folder, if any.

    Returns:
        ``(folder, category_warning)`` -- the newly created gametype folder, and a category/icon
        mismatch warning (see :func:`~in_reach.app.categories.mismatch_warning`) if ``category``
        and ``category_icon`` don't correspond to each other, else ``None``.

    Raises:
        ValueError: If ``title`` fails :func:`is_valid_title`.
    """
    if not is_valid_title(title):
        raise ValueError(f"{title!r} is not a valid project title.")

    root = project_dir.parent
    project_id = _generate_project_id(root)
    folder = root / project_id

    (folder / SCRIPT_DIRNAME).mkdir(parents=True)
    (folder / SETTINGS_DIRNAME).mkdir(parents=True)

    build_dir = folder / BUILD_DIRNAME
    (build_dir / BUILD_DIST_SUBDIR).mkdir(parents=True)
    (build_dir / ".gitignore").write_text(_BUILD_GITIGNORE, encoding="utf-8")

    (folder / NOTES_FILENAME).write_text(_NOTES_TEMPLATE, encoding="utf-8")
    (folder / README_FILENAME).write_text(_README_TEMPLATE, encoding="utf-8")

    resolved_icon = category_icon if category_icon is not None else (default_icon_for(category) or EngineIcon.capture_the_flag)
    warning = mismatch_warning(category, resolved_icon)

    map_entries = maps_io.scan_maps(
        personal_dir=personal_maps_dir, standard_dir=standard_maps_dir, hopper_dir=hopper_maps_dir
    )
    maps_io.write_maps_json(map_entries, project_dir)

    decompile_warning = None
    if source_variant is not None:
        gametype_dir = project_dir / INIT_GAMETYPE_DIRNAME
        gametype_dir.mkdir(parents=True, exist_ok=True)
        copied_variant = gametype_dir / f"{project_id}{_VARIANT_SUFFIX}"
        shutil.copyfile(source_variant, copied_variant)
        decompile_warning = _decompile_source_variant(
            copied_variant,
            folder,
            category=category,
            category_icon=resolved_icon,
            map_entries=map_entries,
            title=title,
            description=description,
        )
    if decompile_warning:
        warning = f"{warning}\n\n{decompile_warning}" if warning else decompile_warning

    env_file.update_env_value(project_dir / _ENV_NAME, PROJECT_DIR_KEY, str(folder))
    return folder, warning
