"""Pulling a script edited in ReachVariantTool back into ``script/output.txt``.

``output.txt`` is what in-reach compiles; the built ``.bin`` is what RVT opens. Settings edited in RVT
were already mirrored back into ``settings/`` when RVT saved, but the script was not, so the next Apply
rebuilt the ``.bin`` from ``output.txt`` and silently discarded whatever was changed in RVT's script
editor. This module is the missing half: notice that RVT changed the script, and put its version in
``output.txt`` -- without ever destroying work that exists only there.

That needs two facts nothing recorded, so ``build/script.autogenerated.json`` keeps them:

* ``text`` -- the script (``decompile_script()``) the ``.bin`` held at the last sync. RVT saving the file
  with the script untouched leaves this unchanged, so it's how "RVT edited the script" is told apart from
  "RVT saved the file".
* ``source_sha256`` -- a digest of ``output.txt`` as it was when that ``.bin`` was built (or pulled into
  it). ``output.txt`` no longer matching it means it has edits no build has seen.

Pulling replaces ``output.txt`` with the decompiled text, so a pull that would lose something -- unapplied
edits, comments, or ``-- @if`` / ``${...}`` build-profile directives (the decompiled script is one profile
already resolved, with no comments) -- is reported as a reason to ask first rather than done silently.

Only for a single-file project. A *linked* project (one with a ``script/project.toml``) compiles from the
linker's output, so a change to the built script has no source to be pulled into.

Pure Python: nothing here loads the native extension, so the GUI process can call it.
"""

from __future__ import annotations

import enum
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from in_reach.app import new_project, script_preprocess, script_project

#: Kept equal to :data:`in_reach.app.rvt.decompile.SCRIPT_FILENAME` (which imports this module, so it
#: can't be imported here); ``tests/app/test_script_sync.py`` checks they agree.
SCRIPT_FILENAME = "output.txt"
SNAPSHOT_FILENAME = "script.autogenerated.json"


@dataclass(frozen=True)
class ScriptSnapshot:
    """See the module docstring. ``source_sha256`` is ``None`` when there was no ``output.txt`` to hash."""

    text: str
    source_sha256: str | None


class PullReason(enum.Enum):
    UNAPPLIED_EDITS = "script/output.txt has edits that haven't been applied yet"
    COMMENTS = "script/output.txt has comments that the script from ReachVariantTool doesn't have"
    PROFILE_DIRECTIVES = (
        "script/output.txt uses build-profile directives (-- @if, ${...}) that the script from "
        "ReachVariantTool doesn't have -- it is one profile already resolved"
    )
    UNSAVED_EDITS = "script/output.txt has unsaved edits in an open tab"


@dataclass(frozen=True)
class PullPlan:
    """What to do about RVT having saved a changed script. ``needed`` is ``False`` when there is nothing
    to pull; otherwise ``reasons`` lists why the user should be asked first (empty: pull silently)."""

    needed: bool
    reasons: tuple[PullReason, ...] = ()


def script_path(folder: Path) -> Path:
    return folder / new_project.SCRIPT_DIRNAME / SCRIPT_FILENAME


def snapshot_path(folder: Path) -> Path:
    return folder / new_project.BUILD_DIRNAME / SNAPSHOT_FILENAME


def _normalized(text: str) -> str:
    return text.replace("\r\n", "\n")


def read_script(folder: Path) -> str | None:
    """``output.txt`` with ``\\n`` line endings, or ``None`` if it doesn't exist."""
    try:
        return _normalized(script_path(folder).read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None


def _digest(text: str | None) -> str | None:
    return None if text is None else hashlib.sha256(_normalized(text).encode("utf-8")).hexdigest()


def read_snapshot(folder: Path) -> ScriptSnapshot | None:
    """The last recorded snapshot, or ``None`` if there is none or it can't be read."""
    try:
        data = json.loads(snapshot_path(folder).read_text(encoding="utf-8"))
        return ScriptSnapshot(text=data["text"], source_sha256=data.get("source_sha256"))
    except (OSError, ValueError, KeyError, TypeError):
        return None


def _write_snapshot(folder: Path, snapshot: ScriptSnapshot) -> None:
    path = snapshot_path(folder)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"text": snapshot.text, "source_sha256": snapshot.source_sha256}
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def record_build(folder: Path, text: str) -> None:
    """A ``.bin`` was just built from ``output.txt`` as it is now, and its script is ``text``."""
    _write_snapshot(folder, ScriptSnapshot(_normalized(text), _digest(read_script(folder))))


def record_sync(folder: Path, text: str) -> None:
    """The ``.bin`` was re-read (RVT saved it) and its script is ``text``. Which ``output.txt`` it
    corresponds to hasn't changed, so the digest is carried over from the last build."""
    previous = read_snapshot(folder)
    _write_snapshot(folder, ScriptSnapshot(_normalized(text), previous.source_sha256 if previous else None))


def plan_pull(folder: Path, before: ScriptSnapshot | None, after: ScriptSnapshot | None) -> PullPlan:
    """Whether RVT's save changed the script, and what a pull would cost.

    Args:
        folder: The gametype project folder.
        before: The snapshot from before the resync that followed the save.
        after: The snapshot that resync wrote.
    """
    if before is None or after is None or before.text == after.text:
        return PullPlan(needed=False)
    if script_project.is_linked(folder):
        # A linked project is built from blocks and modules; output.txt isn't its source, so there is nothing
        # to pull into (and overwriting it would only leave a stray file). RVT can't edit a script anyway.
        return PullPlan(needed=False)
    current = read_script(folder)
    if current == after.text:
        return PullPlan(needed=False)  # output.txt already says what RVT's version says

    reasons: list[PullReason] = []
    if before.source_sha256 is not None and before.source_sha256 != _digest(current):
        reasons.append(PullReason.UNAPPLIED_EDITS)
    if current is not None and script_preprocess.has_comments(current):
        reasons.append(PullReason.COMMENTS)
    if current is not None and script_preprocess.uses_directives(current):
        reasons.append(PullReason.PROFILE_DIRECTIVES)
    return PullPlan(needed=True, reasons=tuple(reasons))


def pull(folder: Path, snapshot: ScriptSnapshot) -> None:
    """Replaces ``output.txt`` with ``snapshot.text`` (RVT's script) and records that ``output.txt`` and
    the ``.bin`` now agree."""
    path = script_path(folder)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(snapshot.text, encoding="utf-8")  # platform newlines, like decompile writes it
    _write_snapshot(folder, ScriptSnapshot(snapshot.text, _digest(snapshot.text)))
