from pathlib import Path

from in_reach.app import apply_settings


def _make_project(tmp_path: Path) -> Path:
    folder = tmp_path / "project"
    (folder / "settings").mkdir(parents=True)
    (folder / "build").mkdir(parents=True)
    return folder


def test_no_changes_when_settings_matches_build(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_has_changes_when_settings_differs_from_build(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 2}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_has_changes_when_build_counterpart_is_missing(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_no_changes_when_settings_has_nothing_to_compare(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_checks_script_settings_and_strings_too(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "settings" / "strings.json").write_text('{"b": 2}', encoding="utf-8")
    (folder / "build" / "strings.autogenerated.json").write_text('{"b": 3}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_apply_settings_changes_copies_every_pair(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "settings" / "script_settings.json").write_text('{"b": 2}', encoding="utf-8")
    (folder / "settings" / "strings.json").write_text('{"c": 3}', encoding="utf-8")

    apply_settings.apply_settings_changes(folder)

    assert (folder / "build" / "settings.autogenerated.json").read_text(encoding="utf-8") == '{"a": 1}'
    assert (folder / "build" / "script_settings.autogenerated.json").read_text(encoding="utf-8") == '{"b": 2}'
    assert (folder / "build" / "strings.autogenerated.json").read_text(encoding="utf-8") == '{"c": 3}'
    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_apply_settings_changes_skips_a_missing_settings_file(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    # script_settings.json/strings.json don't exist -- shouldn't raise, just skipped.

    apply_settings.apply_settings_changes(folder)

    assert (folder / "build" / "settings.autogenerated.json").is_file()
    assert not (folder / "build" / "script_settings.autogenerated.json").exists()


def test_apply_settings_changes_creates_the_build_dir_if_missing(tmp_path: Path) -> None:
    folder = tmp_path / "project"
    (folder / "settings").mkdir(parents=True)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")

    apply_settings.apply_settings_changes(folder)

    assert (folder / "build" / "settings.autogenerated.json").is_file()
