from pathlib import Path

import pytest

from in_reach.app import vcs


def _project(tmp_path: Path) -> Path:
    folder = tmp_path / "abcd1234"
    (folder / "settings").mkdir(parents=True)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "Notes.txt").write_text("hi\n", encoding="utf-8")
    return folder


def test_is_initialized_is_false_before_init(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    assert vcs.is_initialized(folder) is False


def test_init_creates_history_and_a_first_snapshot(tmp_path: Path) -> None:
    folder = _project(tmp_path)

    vcs.init(folder)

    assert vcs.is_initialized(folder) is True
    assert vcs.current_branch(folder) == vcs.DEFAULT_BRANCH
    assert len(vcs.history(folder)) == 1


def test_init_is_a_no_op_if_already_initialized(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "settings" / "settings.json").write_text('{"a": 2}', encoding="utf-8")

    vcs.init(folder)  # should not re-snapshot / wipe history

    assert len(vcs.history(folder)) == 1


def test_init_with_a_stamp_message_stamps_the_first_snapshot(tmp_path: Path) -> None:
    folder = _project(tmp_path)

    vcs.init(folder, stamp_message="gametype init")

    (snapshot,) = vcs.history(folder)
    assert snapshot.is_stamp is True
    assert snapshot.stamp_message == "gametype init"


def test_commit_raises_when_nothing_changed(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    with pytest.raises(ValueError):
        vcs.commit(folder, "nothing to commit")

    assert len(vcs.history(folder)) == 1


def test_commit_snapshots_a_real_edit(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "Notes.txt").write_text("hi\nmore\n", encoding="utf-8")

    result = vcs.commit(folder, "edited notes")

    assert result is not None
    assert len(vcs.history(folder)) == 2
    latest = vcs.history(folder)[0]
    assert latest.is_stamp is False
    assert latest.message == "edited notes"


def test_commit_requires_a_message(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "Notes.txt").write_text("hi\nmore\n", encoding="utf-8")

    with pytest.raises(ValueError):
        vcs.commit(folder, "   ")


def test_commit_before_init_raises(tmp_path: Path) -> None:
    folder = _project(tmp_path)

    with pytest.raises(ValueError):
        vcs.commit(folder, "a message")


# -- uncommitted_changes (PROMPT.md: "we want to add committed changes and uncommitted changes[;]
# when there are uncommitted changes in the repo there should be a notification icon with the
# number of uncommitted changes") -------------------------------------------------------------


def test_uncommitted_changes_is_empty_for_a_clean_project(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    assert vcs.uncommitted_changes(folder) == []


def test_uncommitted_changes_reports_a_modified_file(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "Notes.txt").write_text("hi\nmore\n", encoding="utf-8")

    changes = vcs.uncommitted_changes(folder)

    assert len(changes) == 1
    assert changes[0].path == "Notes.txt"
    assert changes[0].change_type == "modified"


def test_uncommitted_changes_reports_an_added_and_a_removed_file(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "Notes.txt").unlink()
    (folder / "new_file.txt").write_text("new\n", encoding="utf-8")

    changes = {c.path: c.change_type for c in vcs.uncommitted_changes(folder)}

    assert changes == {"Notes.txt": "removed", "new_file.txt": "added"}


def test_uncommitted_changes_ignores_generated_build_output(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    build_dir = folder / "build"
    build_dir.mkdir()
    (build_dir / "settings.autogenerated.json").write_text("{}", encoding="utf-8")

    assert vcs.uncommitted_changes(folder) == []


def test_uncommitted_changes_is_empty_again_right_after_committing(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "Notes.txt").write_text("hi\nmore\n", encoding="utf-8")
    assert vcs.uncommitted_changes(folder) != []

    vcs.commit(folder, "edited notes")

    assert vcs.uncommitted_changes(folder) == []


def test_uncommitted_changes_before_init_is_empty(tmp_path: Path) -> None:
    folder = _project(tmp_path)

    assert vcs.uncommitted_changes(folder) == []


# -- uncommitted_file_diff (PROMPT.md: "when clicking on changes to a file (in the changes tab) a
# tab should appear showing the original on the left and highlighted changes on the right (like
# vscode git)") ----------------------------------------------------------------------------------


def test_uncommitted_file_diff_for_a_modified_file(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "Notes.txt").write_text("hi\nedited\n", encoding="utf-8")

    old, new = vcs.uncommitted_file_diff(folder, "Notes.txt")

    assert old == "hi\n"
    assert new == "hi\nedited\n"


def test_uncommitted_file_diff_for_a_newly_added_file(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "new_file.txt").write_text("brand new\n", encoding="utf-8")

    old, new = vcs.uncommitted_file_diff(folder, "new_file.txt")

    assert old is None
    assert new == "brand new\n"


def test_uncommitted_file_diff_for_a_removed_file(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    (folder / "Notes.txt").unlink()

    old, new = vcs.uncommitted_file_diff(folder, "Notes.txt")

    assert old == "hi\n"
    assert new is None


def test_uncommitted_file_diff_normalizes_crlf_from_the_committed_blob(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    (folder / "Notes.txt").write_bytes(b"line1\r\nline2\r\n")
    vcs.init(folder)
    (folder / "Notes.txt").write_text("line1\nline2\nline3\n", encoding="utf-8")

    old, new = vcs.uncommitted_file_diff(folder, "Notes.txt")

    assert old == "line1\nline2\n"  # not "line1\r\nline2\r\n"
    assert new == "line1\nline2\nline3\n"


def test_uncommitted_file_diff_before_init_is_none_none(tmp_path: Path) -> None:
    folder = _project(tmp_path)

    assert vcs.uncommitted_file_diff(folder, "Notes.txt") == (None, None)


def test_stamp_records_a_labelled_snapshot(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    sha = vcs.stamp(folder, "First release")

    assert isinstance(sha, str) and sha
    snapshot = vcs.history(folder)[0]
    assert snapshot.is_stamp is True
    assert snapshot.stamp_message == "First release"


def test_stamp_requires_a_message(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    with pytest.raises(ValueError):
        vcs.stamp(folder, "   ")


def test_stamp_before_init_raises(tmp_path: Path) -> None:
    folder = _project(tmp_path)

    with pytest.raises(ValueError):
        vcs.stamp(folder, "First release")


def test_last_stamp_finds_the_most_recent_stamp_only(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.stamp(folder, "v1")
    (folder / "Notes.txt").write_text("edit\n", encoding="utf-8")
    vcs.commit(folder, "test change")

    last = vcs.last_stamp(folder)

    assert last is not None
    assert last.stamp_message == "v1"


def test_last_stamp_is_none_when_never_stamped(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    assert vcs.last_stamp(folder) is None


def test_last_saved_at_reflects_the_most_recent_snapshot(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    assert vcs.last_saved_at(folder) is not None


# -- graph_history (PROMPT.md: "we also want to show a git graph of commits, branches and stamps
# instead in vscode style") ---------------------------------------------------------------------


def test_graph_history_is_empty_before_init(tmp_path: Path) -> None:
    folder = _project(tmp_path)

    assert vcs.graph_history(folder) == []


def test_graph_history_marks_the_tip_of_each_branch(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    root_sha = vcs.history(folder)[0].sha
    vcs.create_branch(folder, "feature")
    vcs.switch_branch(folder, vcs.DEFAULT_BRANCH)

    snapshots = vcs.graph_history(folder)

    (root,) = [s for s in snapshots if s.sha == root_sha]
    assert set(root.branches) == {vcs.DEFAULT_BRANCH, "feature"}


def test_graph_history_includes_commits_only_reachable_from_a_non_current_branch(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")
    (folder / "Notes.txt").write_text("feature-only change\n", encoding="utf-8")
    feature_sha = vcs.commit(folder, "feature change")
    vcs.switch_branch(folder, vcs.DEFAULT_BRANCH)

    snapshots = vcs.graph_history(folder)

    assert feature_sha in {s.sha for s in snapshots}


def test_graph_history_records_each_commits_parent(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    root_sha = vcs.history(folder)[0].sha
    (folder / "Notes.txt").write_text("edit\n", encoding="utf-8")
    second_sha = vcs.commit(folder, "edit notes")

    by_sha = {s.sha: s for s in vcs.graph_history(folder)}

    assert by_sha[second_sha].parents == [root_sha]
    assert by_sha[root_sha].parents == []


def test_create_branch_switches_to_the_new_branch(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    vcs.create_branch(folder, "feature")

    assert vcs.current_branch(folder) == "feature"
    assert set(vcs.list_branches(folder)) == {vcs.DEFAULT_BRANCH, "feature"}


def test_create_branch_rejects_a_duplicate_name(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")
    vcs.switch_branch(folder, vcs.DEFAULT_BRANCH)

    with pytest.raises(ValueError):
        vcs.create_branch(folder, "feature")


def test_create_branch_rejects_an_empty_name(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    with pytest.raises(ValueError):
        vcs.create_branch(folder, "  ")


def test_switch_branch_restores_files_from_that_branchs_last_snapshot(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")
    (folder / "Notes.txt").write_text("feature branch content\n", encoding="utf-8")
    vcs.commit(folder, "test change")

    vcs.switch_branch(folder, vcs.DEFAULT_BRANCH)

    assert (folder / "Notes.txt").read_text(encoding="utf-8") == "hi\n"
    assert vcs.current_branch(folder) == vcs.DEFAULT_BRANCH


def test_switch_branch_removes_files_added_only_on_the_other_branch(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")
    (folder / "new_on_feature.txt").write_text("only here\n", encoding="utf-8")
    vcs.commit(folder, "test change")

    vcs.switch_branch(folder, vcs.DEFAULT_BRANCH)

    assert not (folder / "new_on_feature.txt").exists()


def test_switch_branch_never_touches_generated_build_output(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    build_dir = folder / "build"
    build_dir.mkdir()
    generated = build_dir / "settings.autogenerated.json"
    generated.write_text("{}", encoding="utf-8")
    vcs.create_branch(folder, "feature")

    vcs.switch_branch(folder, vcs.DEFAULT_BRANCH)

    assert generated.exists()


def test_switch_branch_rejects_an_unknown_branch(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    with pytest.raises(ValueError):
        vcs.switch_branch(folder, "does-not-exist")


# -- delete_branch ----------------------------------------------------------------------------


def test_delete_branch_removes_a_branch_not_currently_checked_out(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")
    vcs.switch_branch(folder, vcs.DEFAULT_BRANCH)

    vcs.delete_branch(folder, "feature")

    assert vcs.list_branches(folder) == [vcs.DEFAULT_BRANCH]


def test_delete_branch_refuses_the_current_branch(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")  # switches to it

    with pytest.raises(ValueError):
        vcs.delete_branch(folder, "feature")


def test_delete_branch_refuses_the_last_branch(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    with pytest.raises(ValueError):
        vcs.delete_branch(folder, vcs.DEFAULT_BRANCH)


def test_delete_branch_rejects_an_unknown_name(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    with pytest.raises(ValueError):
        vcs.delete_branch(folder, "does-not-exist")


# -- diff ---------------------------------------------------------------------------------------


def test_diff_between_branches_reports_modified_added_and_matches_content(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")
    (folder / "Notes.txt").write_text("hi\nmore\n", encoding="utf-8")
    (folder / "new_file.txt").write_text("new\n", encoding="utf-8")
    vcs.commit(folder, "test change")
    vcs.switch_branch(folder, vcs.DEFAULT_BRANCH)

    diffs = vcs.diff(folder, vcs.DEFAULT_BRANCH, "feature")

    by_path = {d.path: d for d in diffs}
    assert set(by_path) == {"Notes.txt", "new_file.txt"}
    assert by_path["Notes.txt"].change_type == "modified"
    assert "+more" in by_path["Notes.txt"].diff_text
    assert by_path["new_file.txt"].change_type == "added"


def test_diff_reports_a_removed_file(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")
    (folder / "Notes.txt").unlink()
    vcs.commit(folder, "test change")

    diffs = vcs.diff(folder, vcs.DEFAULT_BRANCH, "feature")

    assert len(diffs) == 1
    assert diffs[0].path == "Notes.txt"
    assert diffs[0].change_type == "removed"


def test_diff_is_empty_for_identical_snapshots(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")

    assert vcs.diff(folder, vcs.DEFAULT_BRANCH, "feature") == []


def test_diff_between_two_stamps(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    first = vcs.stamp(folder, "v1")
    (folder / "Notes.txt").write_text("changed\n", encoding="utf-8")
    second = vcs.stamp(folder, "v2")

    diffs = vcs.diff(folder, first, second)

    assert [d.path for d in diffs] == ["Notes.txt"]
    assert diffs[0].change_type == "modified"


def test_diff_treats_undecodable_bytes_as_binary(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    vcs.create_branch(folder, "feature")
    (folder / "image.bin").write_bytes(b"\xff\xfe\x00\x01")
    vcs.commit(folder, "test change")

    diffs = vcs.diff(folder, vcs.DEFAULT_BRANCH, "feature")

    assert diffs[0].diff_text == "Binary file added."


def test_diff_rejects_an_unknown_ref(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    with pytest.raises(ValueError):
        vcs.diff(folder, vcs.DEFAULT_BRANCH, "does-not-exist")


# -- restore_snapshot -----------------------------------------------------------------------------


def test_restore_snapshot_brings_back_an_old_stamps_content(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    first = vcs.stamp(folder, "v1")
    (folder / "Notes.txt").write_text("changed\n", encoding="utf-8")
    vcs.stamp(folder, "v2")

    vcs.restore_snapshot(folder, first)

    assert (folder / "Notes.txt").read_text(encoding="utf-8") == "hi\n"


def test_restore_snapshot_records_a_new_plain_commit_rather_than_rewriting_history(
    tmp_path: Path,
) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    first = vcs.stamp(folder, "v1")
    (folder / "Notes.txt").write_text("changed\n", encoding="utf-8")
    second = vcs.stamp(folder, "v2")
    before = len(vcs.history(folder))

    vcs.restore_snapshot(folder, first)

    after = vcs.history(folder)
    assert len(after) == before + 1
    assert after[0].is_stamp is False  # the restore itself is a plain, non-stamped commit
    assert after[0].message == f"Restored {first[:8]}"
    # both prior stamps are still there, untouched -- history only ever gained an entry.
    assert {s.sha for s in after if s.is_stamp} == {first, second}


def test_restore_snapshot_is_a_no_op_when_it_already_matches_head(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)
    sha = vcs.stamp(folder, "v1")
    before = len(vcs.history(folder))

    vcs.restore_snapshot(folder, sha)

    assert len(vcs.history(folder)) == before


def test_restore_snapshot_rejects_an_unknown_sha(tmp_path: Path) -> None:
    folder = _project(tmp_path)
    vcs.init(folder)

    with pytest.raises(ValueError):
        vcs.restore_snapshot(folder, "not-a-real-sha")
