import json
from pathlib import Path

import pytest

from in_reach.app import apply_settings, new_project, project
from in_reach.app.rvt import rvt_bridge

_JUGGERNAUT_BIN = Path(__file__).parent / "rvt" / "resources" / "juggernaut" / "juggernaut.bin"
_NEEDS_NATIVE_RVT = pytest.mark.skipif(
    not (_JUGGERNAUT_BIN.is_file() and rvt_bridge.is_available()),
    reason="fixture .bin not present, or native _reachvarianttool extension not available on this platform",
)


def _make_project(tmp_path: Path) -> Path:
    folder = tmp_path / "project"
    (folder / "settings").mkdir(parents=True)
    (folder / "build").mkdir(parents=True)
    return folder


def test_no_changes_when_settings_matches_build(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_has_changes_when_settings_differs_from_build(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 2}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_has_changes_when_build_counterpart_is_missing(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_no_changes_when_settings_has_nothing_to_compare(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_generated_at_timestamp_is_ignored_in_the_comparison(tmp_path: Path) -> None:
    # meta.generated_at is restamped fresh with datetime.now() on every extraction (see
    # extraction.py's _extract_meta) -- comparing it directly would read as "unapplied changes"
    # forever, even right after a fully successful Apply (the bug this guards against: the Apply
    # button never got its own "no entry" disabled badge back once it had ever been enabled once).
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text(
        '{"meta": {"title": "x", "generated_at": "2026-01-01T00:00:00Z"}}', encoding="utf-8"
    )
    (folder / "build" / "settings.autogenerated.json").write_text(
        '{"meta": {"title": "x", "generated_at": "2026-06-15T12:30:00Z"}}', encoding="utf-8"
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_a_real_meta_difference_alongside_generated_at_still_counts(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text(
        '{"meta": {"title": "New Title", "generated_at": "2026-01-01T00:00:00Z"}}', encoding="utf-8"
    )
    (folder / "build" / "settings.autogenerated.json").write_text(
        '{"meta": {"title": "Old Title", "generated_at": "2026-06-15T12:30:00Z"}}', encoding="utf-8"
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_checks_script_settings_and_strings_too(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "settings" / "strings.json").write_text('{"b": 2}', encoding="utf-8")
    (folder / "build" / "strings.autogenerated.json").write_text('{"b": 3}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


# -- double-click-Apply regressions (PROMPT.md: "we're having to double click apply for apply to
# work, please assist") -- each of these reproduces a real compile round-trip divergence that used
# to leave settings_have_unapplied_changes() reading True forever after an already-successful Apply,
# no matter how many more times it was clicked.


def test_float_quantization_within_tolerance_is_not_unapplied(tmp_path: Path) -> None:
    # title_update_settings' fixed-point .bin encoding doesn't round-trip an exact float (e.g. 0.5
    # comes back as 0.4999999888241291) -- see test_compile.py's own pytest.approx precedent.
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text(
        json.dumps({"precision_bloom": 0.5}), encoding="utf-8"
    )
    (folder / "build" / "settings.autogenerated.json").write_text(
        json.dumps({"precision_bloom": 0.4999999888241291}), encoding="utf-8"
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_float_difference_beyond_tolerance_still_counts(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text(json.dumps({"precision_bloom": 0.5}), encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text(
        json.dumps({"precision_bloom": 0.8}), encoding="utf-8"
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_bare_string_localized_text_shorthand_matches_full_language_dict(tmp_path: Path) -> None:
    # settings/strings.json's own LocalizedText shorthand -- a bare string means {"english": value}
    # (see models/strings.py) -- while build's freshly re-extracted counterpart always comes back as
    # a full 12-language dict with every other language "". Missing KEYS (not just None values)
    # needs its own normalization, distinct from the plain None-as-"" case below.
    folder = _make_project(tmp_path)
    (folder / "settings" / "strings.json").write_text(
        json.dumps({"teams": [{"index": 0, "name": "Renamed Team"}]}), encoding="utf-8"
    )
    (folder / "build" / "strings.autogenerated.json").write_text(
        json.dumps(
            {
                "teams": [
                    {
                        "index": 0,
                        "name": {
                            "english": "Renamed Team",
                            "japanese": "",
                            "german": "",
                            "french": "",
                            "spanish": "",
                            "mexican": "",
                            "italian": "",
                            "korean": "",
                            "chinese_traditional": "",
                            "chinese_simplified": "",
                            "portugese": "",
                            "polish": "",
                        },
                    }
                ]
            }
        ),
        encoding="utf-8",
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_bare_string_localized_text_shorthand_matches_a_real_localized_build_value(tmp_path: Path) -> None:
    # PROMPT.md: "when making changes to json from in-built game variant the apply changes button
    # doesn't work" -- a professionally-localized (in-built) gametype's own string genuinely has
    # non-empty translations in every language, unlike the all-blank case the test above covers.
    # Editing it via the documented bare-string shorthand (only ever expressing an opinion about
    # English) must not compare English's edit against every *other* language's real, unrelated
    # translation -- doing so used to leave Apply stuck reading "unapplied" forever, since a real
    # translation can never match the "must be empty" a naive full-language normalization assumed.
    folder = _make_project(tmp_path)
    (folder / "settings" / "strings.json").write_text(
        json.dumps({"script_strings": [{"index": 0, "text": "Edited String"}]}), encoding="utf-8"
    )
    (folder / "build" / "strings.autogenerated.json").write_text(
        json.dumps(
            {
                "script_strings": [
                    {
                        "index": 0,
                        "text": {
                            "english": "Edited String",
                            "japanese": "Juggernaut",
                            "german": "Moloch",
                            "french": "Mastodonte",
                            "spanish": "Juggernaut",
                            "mexican": "Juggernaut",
                            "italian": "Juggernaut",
                            "korean": "Juggernaut",
                            "chinese_traditional": "毀滅之王",
                            "chinese_simplified": "",
                            "portugese": "Juggernaut",
                            "polish": "",
                        },
                    }
                ]
            }
        ),
        encoding="utf-8",
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_bare_string_localized_text_shorthand_still_catches_a_real_english_difference(
    tmp_path: Path,
) -> None:
    # The fix must not become "never compare LocalizedText at all" -- an actual, unapplied English
    # edit (build/'s own English slot doesn't match what settings/ specifies) still counts.
    folder = _make_project(tmp_path)
    (folder / "settings" / "strings.json").write_text(
        json.dumps({"script_strings": [{"index": 0, "text": "Brand New Text"}]}), encoding="utf-8"
    )
    (folder / "build" / "strings.autogenerated.json").write_text(
        json.dumps(
            {"script_strings": [{"index": 0, "text": {"english": "Old Text", "japanese": "Juggernaut"}}]}
        ),
        encoding="utf-8",
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_team_name_mirror_in_settings_json_is_ignored(tmp_path: Path) -> None:
    # multiplayer.game_settings.team_settings.teams[].name in settings.json is decompile-only
    # display data -- settings_writer.py's own _apply_team_entry() docstring: a team's real name is
    # never applied from here, only from strings.json's own teams[].name. Renaming a team via
    # strings.json (the correct way) leaves this copy stale forever -- it must not count as pending.
    folder = _make_project(tmp_path)
    team_settings = {"multiplayer": {"game_settings": {"team_settings": {"teams": [{"index": 0, "name": "Old Name"}]}}}}
    build_team_settings = {
        "multiplayer": {"game_settings": {"team_settings": {"teams": [{"index": 0, "name": "New Name"}]}}}
    }
    (folder / "settings" / "settings.json").write_text(json.dumps(team_settings), encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text(json.dumps(build_team_settings), encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_a_real_team_settings_difference_still_counts(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    settings = {"multiplayer": {"game_settings": {"team_settings": {"teams": [{"index": 0, "score_to_win": 1}]}}}}
    build = {"multiplayer": {"game_settings": {"team_settings": {"teams": [{"index": 0, "score_to_win": 2}]}}}}
    (folder / "settings" / "settings.json").write_text(json.dumps(settings), encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text(json.dumps(build), encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_description_string_mirror_in_settings_json_is_ignored(tmp_path: Path) -> None:
    # compile.py's own run_compile() comment: strings.json's meta.description is always applied
    # *after* description_string, unconditionally overwriting it -- so an edit to description_string
    # via settings.json alone can never itself take effect, and must not count as pending.
    folder = _make_project(tmp_path)
    settings = {"multiplayer": {"game_settings": {"metadata": {"description_string": "New description"}}}}
    build = {"multiplayer": {"game_settings": {"metadata": {"description_string": "Old description"}}}}
    (folder / "settings" / "settings.json").write_text(json.dumps(settings), encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text(json.dumps(build), encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is False


@pytest.mark.parametrize(
    "top_level_key,entry",
    [
        ("forge_labels", {"name": "old"}),
        ("scripted_player_traits", {"name": "old", "desc": "old"}),
        ("scripted_stats", {"name": "old"}),
    ],
)
def test_script_settings_text_mirrors_are_ignored(tmp_path: Path, top_level_key: str, entry: dict) -> None:
    # forge_labels[].name / scripted_player_traits[].name+desc are resolved script_strings-table
    # lookups computed only at extraction time (settings_writer.py's own module docstring: "Text
    # fields ... are deliberately NOT applied by this module at all") -- renaming the backing entry
    # via strings.json leaves these settings.json mirrors stale forever, same as team names.
    folder = _make_project(tmp_path)
    old_entry = dict(entry)
    new_entry = {**entry, "name": "new", **({"desc": "new"} if "desc" in entry else {})}
    (folder / "settings" / "script_settings.json").write_text(json.dumps({top_level_key: [old_entry]}), encoding="utf-8")
    (folder / "build" / "script_settings.autogenerated.json").write_text(
        json.dumps({top_level_key: [new_entry]}), encoding="utf-8"
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_scripted_option_and_value_text_mirrors_are_ignored(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    old = {
        "scripted_options": [
            {
                "name": "old",
                "desc": "old",
                "values": [{"name": "old", "desc": "old", "value": 0}],
                "range_default": {"name": "old", "desc": "old", "value": 0},
                "range_min": {"name": "old", "desc": "old", "value": 0},
                "range_max": {"name": "old", "desc": "old", "value": 0},
            }
        ]
    }
    new = {
        "scripted_options": [
            {
                "name": "new",
                "desc": "new",
                "values": [{"name": "new", "desc": "new", "value": 0}],
                "range_default": {"name": "new", "desc": "new", "value": 0},
                "range_min": {"name": "new", "desc": "new", "value": 0},
                "range_max": {"name": "new", "desc": "new", "value": 0},
            }
        ]
    }
    (folder / "settings" / "script_settings.json").write_text(json.dumps(old), encoding="utf-8")
    (folder / "build" / "script_settings.autogenerated.json").write_text(json.dumps(new), encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_forge_label_resolved_object_type_and_team_names_are_ignored(tmp_path: Path) -> None:
    # required_object_type_name/required_team_name are resolved (rvt.object_type_name()/the map's
    # own configured team list, see extraction.py's _object_type_name()/_resolve_const_team_name())
    # only at extraction time -- settings_writer.py's own _apply_forge_label() never writes them.
    # Editing the raw required_object_type/required_team a label actually applies leaves these
    # resolved-display mirrors stale, same bug class as team names.
    folder = _make_project(tmp_path)
    old = {"forge_labels": [{"required_object_type": 5, "required_object_type_name": "Skull", "required_team": "team_1", "required_team_name": None}]}
    new = {
        "forge_labels": [
            {"required_object_type": 5, "required_object_type_name": "Energy Sword", "required_team": "team_1", "required_team_name": "Crimson"}
        ]
    }
    (folder / "settings" / "script_settings.json").write_text(json.dumps(old), encoding="utf-8")
    (folder / "build" / "script_settings.autogenerated.json").write_text(json.dumps(new), encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_required_object_type_names_mirror_is_ignored(tmp_path: Path) -> None:
    # RequiredObjectTypes.object_type_names is a resolved-display parallel list to
    # object_type_indices (the field settings_writer.py's _apply_required_object_types() actually
    # applies) -- editing object_type_indices leaves this mirror stale in settings.json until the
    # next full resync, the same as everything else here.
    folder = _make_project(tmp_path)
    old = {"required_object_types": {"object_type_indices": [5], "object_type_names": ["Skull"]}}
    new = {"required_object_types": {"object_type_indices": [5], "object_type_names": ["Energy Sword"]}}
    (folder / "settings" / "script_settings.json").write_text(json.dumps(old), encoding="utf-8")
    (folder / "build" / "script_settings.autogenerated.json").write_text(json.dumps(new), encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_a_real_required_object_type_indices_difference_still_counts(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    old = {"required_object_types": {"object_type_indices": [5], "object_type_names": ["Skull"]}}
    new = {"required_object_types": {"object_type_indices": [5, 20], "object_type_names": ["Skull", "Energy Sword"]}}
    (folder / "settings" / "script_settings.json").write_text(json.dumps(old), encoding="utf-8")
    (folder / "build" / "script_settings.autogenerated.json").write_text(json.dumps(new), encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_a_real_scripted_option_value_difference_still_counts(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    old = {"scripted_options": [{"values": [{"value": 0}]}]}
    new = {"scripted_options": [{"values": [{"value": 1}]}]}
    (folder / "settings" / "script_settings.json").write_text(json.dumps(old), encoding="utf-8")
    (folder / "build" / "script_settings.autogenerated.json").write_text(json.dumps(new), encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


# -- apply_settings_changes (PROMPT.md: "applying changes should try and compile the jsons into a
# gametype") -- exercises the real compile pipeline end to end, so these need the actual bundled
# native extension and a real .bin fixture, not fakes; see test_compile.py for pure-orchestration
# coverage against a faked variant.


@pytest.fixture
def _project(tmp_path: Path) -> tuple[Path, Path]:
    project_dir = project.get_project_dir(tmp_path)
    project_dir.mkdir(parents=True)
    folder, warning = new_project.create_gametype_project(project_dir, "Apply Test", source_variant=_JUGGERNAUT_BIN)
    assert warning is None
    return project_dir, folder


@_NEEDS_NATIVE_RVT
def test_apply_settings_changes_compiles_and_writes_the_build_snapshot(_project: tuple[Path, Path]) -> None:
    project_dir, folder = _project
    assert apply_settings.settings_have_unapplied_changes(folder) is False  # freshly decompiled -- nothing edited yet

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert result.output_path == folder / "build" / "dist" / f"{folder.name}.bin"
    assert result.output_path.is_file()
    assert (folder / "build" / "settings.autogenerated.json").is_file()
    assert (folder / "build" / "script_settings.autogenerated.json").is_file()
    assert (folder / "build" / "strings.autogenerated.json").is_file()


@_NEEDS_NATIVE_RVT
def test_apply_settings_changes_has_nothing_left_to_apply_afterward(_project: tuple[Path, Path]) -> None:
    # Regression guard for the real end-to-end pipeline (not just the pure-JSON unit tests above):
    # a successful Apply with no further hand-edits should leave the Apply button disabled again.
    project_dir, folder = _project

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert apply_settings.settings_have_unapplied_changes(folder) is False


@_NEEDS_NATIVE_RVT
def test_apply_settings_changes_reports_a_bad_script_and_writes_nothing(_project: tuple[Path, Path]) -> None:
    project_dir, folder = _project
    script_path = folder / "script" / "output.txt"
    script_path.write_text("this is not valid megalo script @#$%", encoding="utf-8")
    dist_bin = folder / "build" / "dist" / f"{folder.name}.bin"
    assert not dist_bin.exists()

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is False
    assert result.fatal_errors or result.errors
    assert not dist_bin.exists()


@_NEEDS_NATIVE_RVT
def test_apply_settings_changes_reports_invalid_settings_json_and_writes_nothing(
    _project: tuple[Path, Path],
) -> None:
    project_dir, folder = _project
    (folder / "settings" / "settings.json").write_text("{not valid json", encoding="utf-8")
    dist_bin = folder / "build" / "dist" / f"{folder.name}.bin"

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is False
    assert result.failure is not None
    assert not dist_bin.exists()


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data), encoding="utf-8")


@_NEEDS_NATIVE_RVT
def test_renaming_a_team_via_strings_json_leaves_nothing_pending(_project: tuple[Path, Path]) -> None:
    # PROMPT.md: "we're having to double click apply for apply to work" -- a team rename (the
    # correct workflow, via strings.json's own bare-string LocalizedText shorthand) used to leave
    # settings.json's own decompile-only teams[].name mirror permanently stale.
    project_dir, folder = _project
    strings_path = folder / "settings" / "strings.json"
    strings_data = _read_json(strings_path)
    strings_data["teams"][0]["name"] = "Renamed Team"
    _write_json(strings_path, strings_data)

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert apply_settings.settings_have_unapplied_changes(folder) is False


@_NEEDS_NATIVE_RVT
def test_renaming_a_blank_script_string_leaves_nothing_pending(_project: tuple[Path, Path]) -> None:
    # Setting a previously-blank script_strings entry's text (bare-string shorthand) also feeds
    # script_settings.json's own scripted_options[].values[].desc mirror (resolved from the same
    # string-table index) -- that mirror used to stay stale after Apply too.
    project_dir, folder = _project
    strings_path = folder / "settings" / "strings.json"
    strings_data = _read_json(strings_path)
    blank_index = next(
        entry["index"]
        for entry in strings_data["script_strings"]
        if not (isinstance(entry["text"], dict) and any(entry["text"].values()))
    )
    entry = next(e for e in strings_data["script_strings"] if e["index"] == blank_index)
    entry["text"] = "Brand New Label"
    _write_json(strings_path, strings_data)

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert apply_settings.settings_have_unapplied_changes(folder) is False


@_NEEDS_NATIVE_RVT
def test_renaming_a_genuinely_localized_script_string_leaves_nothing_pending(
    _project: tuple[Path, Path],
) -> None:
    # PROMPT.md: "when making changes to json from in-built game variant the apply changes button
    # doesn't work" -- unlike the blank-entry test above, this specifically picks an entry that
    # already has *real* non-English content (Juggernaut is a professionally localized, in-built
    # gametype) -- the exact case that used to leave Apply stuck reading "unapplied" forever, no
    # matter how many more times it was clicked, since the old comparison forced every language
    # the edit didn't re-specify to read as "must now be empty," which a real translation can
    # never satisfy.
    project_dir, folder = _project
    strings_path = folder / "settings" / "strings.json"
    strings_data = _read_json(strings_path)
    localized_index = next(
        entry["index"]
        for entry in strings_data["script_strings"]
        if isinstance(entry["text"], dict) and any(entry["text"].get(lang) for lang in ("japanese", "german"))
    )
    entry = next(e for e in strings_data["script_strings"] if e["index"] == localized_index)
    entry["text"] = "Brand New Label"
    _write_json(strings_path, strings_data)

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert apply_settings.settings_have_unapplied_changes(folder) is False


@_NEEDS_NATIVE_RVT
def test_editing_description_via_settings_json_leaves_nothing_pending(_project: tuple[Path, Path]) -> None:
    # metadata.description_string in settings.json is always overwritten by strings.json's own
    # meta.description on the very next step of the same compile (see compile.py's run_compile()
    # comment) -- editing it directly can never itself take effect, so it must not read as pending.
    project_dir, folder = _project
    settings_path = folder / "settings" / "settings.json"
    settings_data = _read_json(settings_path)
    settings_data["multiplayer"]["game_settings"]["metadata"]["description_string"] = "A brand new description"
    _write_json(settings_path, settings_data)

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert apply_settings.settings_have_unapplied_changes(folder) is False


@_NEEDS_NATIVE_RVT
def test_editing_required_object_types_leaves_nothing_pending(_project: tuple[Path, Path]) -> None:
    # object_type_names is a resolved-display mirror of object_type_indices (the field that
    # actually gets applied) -- editing the indices used to leave settings.json's own copy of the
    # resolved names permanently stale relative to build's freshly re-extracted one.
    project_dir, folder = _project
    script_settings_path = folder / "settings" / "script_settings.json"
    script_settings_data = _read_json(script_settings_path)
    script_settings_data["required_object_types"]["object_type_indices"] = [1, 2, 3]
    _write_json(script_settings_path, script_settings_data)

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert apply_settings.settings_have_unapplied_changes(folder) is False
