import json
from pathlib import Path

import pytest

from in_reach.app import env_file, new_project
from in_reach.app.categories import EngineCategory, EngineIcon


@pytest.fixture
def project_dir(tmp_path: Path) -> Path:
    project = tmp_path / ".in-reach"
    project.mkdir()
    (project / ".env").write_text("", encoding="utf-8")
    return project


@pytest.mark.parametrize(
    "title",
    [
        "My Gametype",
        "a",
        "x" * new_project.MAX_TITLE_LENGTH,
        "CONTEST",
        # No longer folder-name rules -- a title can contain anything a Windows folder name
        # couldn't, since it no longer names the project folder (see is_valid_title's docstring).
        "no/slashes needed now",
        "trailing space ",
        "trailing dot.",
        "CON",
    ],
)
def test_valid_titles(title: str) -> None:
    assert new_project.is_valid_title(title) is True


@pytest.mark.parametrize("title", ["", "   ", "x" * (new_project.MAX_TITLE_LENGTH + 1)])
def test_invalid_titles(title: str) -> None:
    assert new_project.is_valid_title(title) is False


def test_create_gametype_project_names_the_folder_with_a_generated_id_not_the_title(
    project_dir: Path, tmp_path: Path
) -> None:
    folder, warning = new_project.create_gametype_project(project_dir, "Slayer Plus", "A better slayer")

    assert warning is None
    assert folder.parent == tmp_path
    assert folder.name != "Slayer Plus"
    assert len(folder.name) == new_project.PROJECT_ID_LENGTH
    assert (folder / "settings").is_dir()
    assert (folder / "edit" / "rvt").is_dir()
    assert (folder / "build" / "dist").is_dir()
    # build/ is regenerated from settings/, so it ignores itself rather than relying on the user's
    # own repo-level .gitignore.
    assert (folder / "build" / ".gitignore").read_text(encoding="utf-8") == "*\n!.gitignore\n"

    readme = (folder / "README.md").read_text(encoding="utf-8")
    assert "# Slayer Plus" in readme
    assert "A better slayer" in readme
    assert folder.name in readme


def test_create_gametype_project_points_project_dir_at_the_new_folder(project_dir: Path) -> None:
    folder, _warning = new_project.create_gametype_project(project_dir, "Slayer Plus")

    values = env_file.get_env_values(project_dir / ".env")
    assert values[new_project.PROJECT_DIR_KEY] == str(folder)


def test_create_gametype_project_without_a_description_still_writes_a_readme(project_dir: Path) -> None:
    folder, _warning = new_project.create_gametype_project(project_dir, "Blank One")

    assert "_No description._" in (folder / "README.md").read_text(encoding="utf-8")


def test_description_max_length_is_137_and_unrelated_to_windows_naming_rules() -> None:
    assert new_project.MAX_DESCRIPTION_LENGTH == 137


def test_description_accepts_characters_a_windows_folder_name_would_reject(project_dir: Path) -> None:
    description = 'Faster / stronger * better: now with "quotes" <and> a trailing dot.'

    folder, _warning = new_project.create_gametype_project(project_dir, "Slayer Plus", description)

    assert description in (folder / "README.md").read_text(encoding="utf-8")


def test_create_gametype_project_copies_the_source_variant_in_named_after_the_id(
    project_dir: Path, tmp_path: Path
) -> None:
    source = tmp_path / "variants" / "Original.bin"
    source.parent.mkdir()
    source.write_bytes(b"\x00variant")

    folder, _warning = new_project.create_gametype_project(
        project_dir, "Slayer Plus", source_variant=source
    )

    copied = project_dir / new_project.INIT_GAMETYPE_DIRNAME / f"{folder.name}.bin"
    assert copied.read_bytes() == b"\x00variant"


def test_create_gametype_project_decompiles_a_real_source_variant(
    project_dir: Path,
) -> None:
    """PROMPT.md: "when a project is selected the gametype is decompiled as in the previous
    repos" -- exercises the real bundled native extension against a real .bin fixture, not fakes."""
    source = Path(__file__).parent / "rvt" / "resources" / "juggernaut" / "juggernaut.bin"

    folder, warning = new_project.create_gametype_project(project_dir, "Slayer Plus", source_variant=source)

    assert warning is None
    settings = json.loads((folder / "settings" / "settings.json").read_text(encoding="utf-8"))
    # PROMPT.md: "when setting a title and description, this is not being set in settings.json" --
    # this project's own title (typed into the New Project dialog) now overrides whatever the
    # source .bin's own header happened to say ("JUGGERNAUT"), same as category/category_icon.
    assert settings["meta"]["title"] == "Slayer Plus"
    assert (folder / "settings" / "script_settings.json").is_file()
    assert (folder / "settings" / "strings.json").is_file()
    assert (folder / "settings" / "valid_maps.json").is_file()
    script = (folder / "edit" / "rvt" / "script.txt").read_text(encoding="utf-8")
    assert "declare" in script
    assert (folder / "build" / "stats.autogenerated.json").is_file()


def test_create_gametype_project_surfaces_a_decompile_failure_as_a_warning_not_a_crash(
    project_dir: Path,
) -> None:
    """A .bin the native extension can't load shouldn't block the project from being created --
    see new_project._decompile_source_variant()'s docstring."""
    bad_source = project_dir.parent / "not-a-real-variant.bin"
    bad_source.write_bytes(b"not a real .bin")

    folder, warning = new_project.create_gametype_project(project_dir, "Slayer Plus", source_variant=bad_source)

    assert folder.is_dir()
    assert warning is not None
    assert not (folder / "edit" / "rvt" / "script.txt").is_file()


def test_create_gametype_project_rejects_an_empty_title(project_dir: Path) -> None:
    with pytest.raises(ValueError):
        new_project.create_gametype_project(project_dir, "   ")


def test_two_projects_created_in_a_row_get_different_ids(project_dir: Path) -> None:
    first, _warning = new_project.create_gametype_project(project_dir, "One")
    second, _warning = new_project.create_gametype_project(project_dir, "Two")

    assert first != second


# -- category / category_icon ------------------------------------------------------------------

_JUGGERNAUT_BIN = Path(__file__).parent / "rvt" / "resources" / "juggernaut" / "juggernaut.bin"


def test_create_gametype_project_defaults_to_no_category_and_no_warning(project_dir: Path) -> None:
    folder, warning = new_project.create_gametype_project(
        project_dir, "Blank", source_variant=_JUGGERNAUT_BIN
    )

    assert warning is None
    document = (folder / "settings" / "settings.json").read_text(encoding="utf-8")
    assert '"category": "none"' in document


def test_create_gametype_project_writes_a_matching_category_and_icon_by_default(
    project_dir: Path,
) -> None:
    folder, warning = new_project.create_gametype_project(
        project_dir, "Slayer Plus", category=EngineCategory.slayer, source_variant=_JUGGERNAUT_BIN
    )

    assert warning is None
    document = (folder / "settings" / "settings.json").read_text(encoding="utf-8")
    assert '"category": "slayer"' in document
    assert '"category_icon": "slayer"' in document


def test_create_gametype_project_reports_a_deliberate_mismatch(project_dir: Path) -> None:
    folder, warning = new_project.create_gametype_project(
        project_dir,
        "Odd Slayer",
        category=EngineCategory.slayer,
        category_icon=EngineIcon.oddball,
        source_variant=_JUGGERNAUT_BIN,
    )

    assert warning is not None
    assert "Slayer" in warning and "Oddball" in warning
    document = (folder / "settings" / "settings.json").read_text(encoding="utf-8")
    assert '"category_icon": "oddball"' in document


def test_create_gametype_project_with_no_source_variant_writes_no_settings_json(
    project_dir: Path,
) -> None:
    # Category/category_icon now live in the decompiled settings.json (PROMPT.md) -- a truly blank
    # project (no .bin to decompile at all) simply has nowhere to persist them, same as it already
    # had no edit/rvt/script.txt content in that case.
    folder, warning = new_project.create_gametype_project(
        project_dir, "Blank", category=EngineCategory.slayer
    )

    assert warning is None
    assert not (folder / "settings" / "settings.json").exists()


# -- title / description --------------------------------------------------------------------------


def test_create_gametype_project_stamps_title_and_description_into_settings_json(
    project_dir: Path,
) -> None:
    folder, warning = new_project.create_gametype_project(
        project_dir, "Slayer Plus", "A friendly slayer variant", source_variant=_JUGGERNAUT_BIN
    )

    assert warning is None
    settings = json.loads((folder / "settings" / "settings.json").read_text(encoding="utf-8"))
    assert settings["meta"]["title"] == "Slayer Plus"
    assert settings["meta"]["description"] == "A friendly slayer variant"


# -- maps.json ------------------------------------------------------------------------------------


def test_create_gametype_project_scans_map_folders_into_maps_json(
    project_dir: Path, tmp_path: Path
) -> None:
    from mvar_fixtures import build_chdr_bytes

    maps_dir = tmp_path / "maps"
    maps_dir.mkdir()
    (maps_dir / "Forge.mvar").write_bytes(build_chdr_bytes(title="My Forge Map", map_id=3006))

    folder, _warning = new_project.create_gametype_project(
        project_dir, "Slayer Plus", personal_maps_dir=maps_dir
    )

    # PROMPT.md: the shared/master scan lives once in .in-reach, not duplicated per project --
    # "there should be no maps dir anymore".
    assert (project_dir / "maps.json").is_file()
    assert not (folder / "maps.json").exists()
    assert not (folder / "maps").exists()
    document = (project_dir / "maps.json").read_text(encoding="utf-8")
    assert "My Forge Map" in document


def test_create_gametype_project_with_no_map_folders_still_writes_an_empty_maps_json(
    project_dir: Path,
) -> None:
    new_project.create_gametype_project(project_dir, "Blank")

    document = (project_dir / "maps.json").read_text(encoding="utf-8")
    assert '"maps": []' in document


def test_two_projects_created_in_a_row_share_the_same_maps_json(
    project_dir: Path, tmp_path: Path
) -> None:
    from mvar_fixtures import build_chdr_bytes

    maps_dir = tmp_path / "maps"
    maps_dir.mkdir()
    (maps_dir / "Forge.mvar").write_bytes(build_chdr_bytes(title="My Forge Map", map_id=3006))

    first, _warning = new_project.create_gametype_project(project_dir, "One")
    second, _warning = new_project.create_gametype_project(
        project_dir, "Two", personal_maps_dir=maps_dir
    )

    # The first project's own creation predates the maps folder existing at all -- confirms the
    # second project's scan overwrote the one shared file rather than each project getting (or
    # needing) its own.
    document = (project_dir / "maps.json").read_text(encoding="utf-8")
    assert "My Forge Map" in document
    assert not (first / "maps.json").exists()
    assert not (second / "maps.json").exists()


# -- read_project_title -----------------------------------------------------------------------


def test_read_project_title_reads_back_the_readmes_heading(project_dir: Path) -> None:
    folder, _warning = new_project.create_gametype_project(project_dir, "Slayer Plus")

    assert new_project.read_project_title(folder) == "Slayer Plus"


def test_read_project_title_falls_back_to_the_folder_name_without_a_readme(tmp_path: Path) -> None:
    folder = tmp_path / "abcd1234"
    folder.mkdir()

    assert new_project.read_project_title(folder) == "abcd1234"


# -- list_variants ----------------------------------------------------------------------------


def test_list_variants_returns_bins_by_name_case_insensitively(tmp_path: Path) -> None:
    folder = tmp_path / "game_variants"
    folder.mkdir()
    for name in ("zulu.bin", "Alpha.bin", "notes.txt"):
        (folder / name).write_bytes(b"")
    (folder / "nested").mkdir()

    assert new_project.list_variants(folder) == [
        ("Alpha", folder / "Alpha.bin"),
        ("zulu", folder / "zulu.bin"),
    ]


def test_list_variants_of_a_missing_folder_is_empty(tmp_path: Path) -> None:
    assert new_project.list_variants(tmp_path / "nope") == []


# -- source_variant_path ------------------------------------------------------------------------


def test_source_variant_path_matches_where_create_gametype_project_copies_it(
    project_dir: Path,
) -> None:
    source = project_dir.parent / "Original.bin"
    source.write_bytes(b"\x00variant")

    folder, _warning = new_project.create_gametype_project(
        project_dir, "Slayer Plus", source_variant=source
    )

    expected = new_project.source_variant_path(project_dir, folder)
    assert expected.is_file()
    assert expected.read_bytes() == b"\x00variant"


# -- is_generated_file -------------------------------------------------------------------------


@pytest.mark.parametrize(
    "relative",
    [
        "build/dist/test.bin",
        "build/dist/test.mglo",
        "build/settings.autogenerated.json",
        "build/script_settings.autogenerated.json",
        "build/strings.autogenerated.json",
        "build/stats.autogenerated.json",
        "settings.autogenerated.json",  # the name alone is enough, regardless of folder
        # PROMPT.md: "schema files should be non-editable (by hand)".
        "settings/schema/settings.schema.json",
        "settings/schema/script_settings.schema.json",
        "settings/schema/strings.schema.json",
        "settings.schema.json",  # the name alone is enough, regardless of folder
    ],
)
def test_is_generated_file_true_for_build_output(tmp_path: Path, relative: str) -> None:
    assert new_project.is_generated_file(tmp_path / relative) is True


@pytest.mark.parametrize(
    "relative",
    [
        "settings/settings.json",
        "settings/script_settings.json",
        "settings/strings.json",
        "settings/valid_maps.json",
        "edit/rvt/script.txt",
        "README.md",
        "maps.json",
    ],
)
def test_is_generated_file_false_for_hand_editable_source(tmp_path: Path, relative: str) -> None:
    assert new_project.is_generated_file(tmp_path / relative) is False
