from pathlib import Path

import pytest

from in_reach.app import apply_settings, new_project, project

_JUGGERNAUT_BIN = Path(__file__).parent / "rvt" / "resources" / "juggernaut" / "juggernaut.bin"


def _make_project(tmp_path: Path) -> Path:
    folder = tmp_path / "project"
    (folder / "settings").mkdir(parents=True)
    (folder / "build").mkdir(parents=True)
    return folder


def test_no_changes_when_settings_matches_build(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_has_changes_when_settings_differs_from_build(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 2}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_has_changes_when_build_counterpart_is_missing(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_no_changes_when_settings_has_nothing_to_compare(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_generated_at_timestamp_is_ignored_in_the_comparison(tmp_path: Path) -> None:
    # meta.generated_at is restamped fresh with datetime.now() on every extraction (see
    # extraction.py's _extract_meta) -- comparing it directly would read as "unapplied changes"
    # forever, even right after a fully successful Apply (the bug this guards against: the Apply
    # button never got its own "no entry" disabled badge back once it had ever been enabled once).
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text(
        '{"meta": {"title": "x", "generated_at": "2026-01-01T00:00:00Z"}}', encoding="utf-8"
    )
    (folder / "build" / "settings.autogenerated.json").write_text(
        '{"meta": {"title": "x", "generated_at": "2026-06-15T12:30:00Z"}}', encoding="utf-8"
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is False


def test_a_real_meta_difference_alongside_generated_at_still_counts(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text(
        '{"meta": {"title": "New Title", "generated_at": "2026-01-01T00:00:00Z"}}', encoding="utf-8"
    )
    (folder / "build" / "settings.autogenerated.json").write_text(
        '{"meta": {"title": "Old Title", "generated_at": "2026-06-15T12:30:00Z"}}', encoding="utf-8"
    )

    assert apply_settings.settings_have_unapplied_changes(folder) is True


def test_checks_script_settings_and_strings_too(tmp_path: Path) -> None:
    folder = _make_project(tmp_path)
    (folder / "settings" / "settings.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "build" / "settings.autogenerated.json").write_text('{"a": 1}', encoding="utf-8")
    (folder / "settings" / "strings.json").write_text('{"b": 2}', encoding="utf-8")
    (folder / "build" / "strings.autogenerated.json").write_text('{"b": 3}', encoding="utf-8")

    assert apply_settings.settings_have_unapplied_changes(folder) is True


# -- apply_settings_changes (PROMPT.md: "applying changes should try and compile the jsons into a
# gametype") -- exercises the real compile pipeline end to end, so these need the actual bundled
# native extension and a real .bin fixture, not fakes; see test_compile.py for pure-orchestration
# coverage against a faked variant.


@pytest.fixture
def _project(tmp_path: Path) -> tuple[Path, Path]:
    project_dir = project.get_project_dir(tmp_path)
    project_dir.mkdir(parents=True)
    folder, warning = new_project.create_gametype_project(project_dir, "Apply Test", source_variant=_JUGGERNAUT_BIN)
    assert warning is None
    return project_dir, folder


@pytest.mark.skipif(not _JUGGERNAUT_BIN.is_file(), reason="fixture .bin not present")
def test_apply_settings_changes_compiles_and_writes_the_build_snapshot(_project: tuple[Path, Path]) -> None:
    project_dir, folder = _project
    assert apply_settings.settings_have_unapplied_changes(folder) is False  # freshly decompiled -- nothing edited yet

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert result.output_path == folder / "build" / "dist" / f"{folder.name}.bin"
    assert result.output_path.is_file()
    assert (folder / "build" / "settings.autogenerated.json").is_file()
    assert (folder / "build" / "script_settings.autogenerated.json").is_file()
    assert (folder / "build" / "strings.autogenerated.json").is_file()


@pytest.mark.skipif(not _JUGGERNAUT_BIN.is_file(), reason="fixture .bin not present")
def test_apply_settings_changes_has_nothing_left_to_apply_afterward(_project: tuple[Path, Path]) -> None:
    # Regression guard for the real end-to-end pipeline (not just the pure-JSON unit tests above):
    # a successful Apply with no further hand-edits should leave the Apply button disabled again.
    project_dir, folder = _project

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is True
    assert apply_settings.settings_have_unapplied_changes(folder) is False


@pytest.mark.skipif(not _JUGGERNAUT_BIN.is_file(), reason="fixture .bin not present")
def test_apply_settings_changes_reports_a_bad_script_and_writes_nothing(_project: tuple[Path, Path]) -> None:
    project_dir, folder = _project
    script_path = folder / "script" / "game.txt"
    script_path.write_text("this is not valid megalo script @#$%", encoding="utf-8")
    dist_bin = folder / "build" / "dist" / f"{folder.name}.bin"
    assert not dist_bin.exists()

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is False
    assert result.fatal_errors or result.errors
    assert not dist_bin.exists()


@pytest.mark.skipif(not _JUGGERNAUT_BIN.is_file(), reason="fixture .bin not present")
def test_apply_settings_changes_reports_invalid_settings_json_and_writes_nothing(
    _project: tuple[Path, Path],
) -> None:
    project_dir, folder = _project
    (folder / "settings" / "settings.json").write_text("{not valid json", encoding="utf-8")
    dist_bin = folder / "build" / "dist" / f"{folder.name}.bin"

    result = apply_settings.apply_settings_changes(project_dir, folder)

    assert result.success is False
    assert result.failure is not None
    assert not dist_bin.exists()
