"""Compiles a project's ``settings/`` (settings.json/script_settings.json/strings.json) and
``script/output.txt`` into a real game variant (PROMPT.md: "applying changes should try and
compile the jsons into a gametype and i[f] it fails then dont allow application (raise errors in
text window - although hopefully our schema validation should catch this)").

Ported/adapted from ``in-reach-v2``'s own ``app/compile.py::run_compile`` -- always rebuilds from a
fixed base, never mutates ``build/``'s own prior output incrementally: preferably this project's
own ``.in-reach/init_gametype/<id>.bin`` (see
:func:`~in_reach.app.new_project.source_variant_path` -- the packaged blank always has zero
forge-labels/scripted-options/player-traits-sets/HUD-widgets, and the Megalo compiler can't create
a slot in any of those tables just because a script references it by index -- only forge labels
self-vivify, by name, and only as a notice, not an error -- so a script that references any of the
others by index can only ever compile against a base that already has that many slots; loading
this project's own record of its original source ``.bin`` preserves that instead of starting from
zero every time), falling back to the packaged blank (multiplayer or Firefight, picked from
``settings/settings.json``'s own ``meta.is_multiplayer``, see
:mod:`in_reach.app.blank_variant`) only when that record is missing.

Unlike v2, this doesn't write a ``.mglo`` (RVT's own hot-reload-into-MCC format) -- that's a
separate feature (``inreach load``) this app has no equivalent of yet, not part of what PROMPT.md
asked for here.

A successful ``save=True`` run writes ``build/dist/<folder-name>.bin`` plus
``build/*.autogenerated.json`` -- the latter via :func:`~in_reach.app.rvt.decompile.
write_build_snapshot`, re-extracted from the just-compiled ``variant`` (not a copy of
``settings/``'s own input), so it reflects exactly what the compiler actually produced.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel

from in_reach.app import new_project
from in_reach.app.blank_variant import resolve_blank_variant

from . import decompile, settings_io, settings_writer, strings_io, strings_writer
from .decompile import write_build_snapshot
from .rvt_bridge import get_rvt
from .settings_io import load_game_settings


class BuildMessage(BaseModel):
    line: int
    col: int
    text: str


class BuildResult(BaseModel):
    """``fatal_errors``/``errors``/``warnings``/``notices`` come straight from the Megalo compiler
    when a script was compiled (empty otherwise); ``failure`` holds a human-readable reason for
    anything the compiler log can't already explain (a missing/unreadable file, a settings-apply
    ``ValueError``, a save failure). Named ``Build*`` (not ``Compile*``) specifically to avoid
    confusion with the native ``_reachvarianttool.CompileMessage``/``CompileResult`` classes."""

    success: bool
    fatal_errors: list[BuildMessage] = []
    errors: list[BuildMessage] = []
    warnings: list[BuildMessage] = []
    notices: list[BuildMessage] = []
    failure: str | None = None
    output_path: Path | None = None


def _messages(items) -> list[BuildMessage]:
    return [BuildMessage(line=m.line, col=m.col, text=m.text) for m in items]


def format_build_result(result: BuildResult) -> str:
    """A single multi-line, user-facing message summarizing everything a failed (or
    warning-carrying) :class:`BuildResult` reported -- what the Apply button's own failure dialog
    shows (PROMPT.md: "raise errors in text window")."""
    lines: list[str] = []
    if result.failure:
        lines.append(result.failure)
    for label, messages in (
        ("fatal error", result.fatal_errors),
        ("error", result.errors),
        ("warning", result.warnings),
        ("notice", result.notices),
    ):
        for message in messages:
            lines.append(f"{label} ({message.line}:{message.col}): {message.text}")
    return "\n".join(lines)


def run_compile(project_dir: Path, folder: Path, *, save: bool) -> BuildResult:
    """Builds ``folder``'s project from ``settings/``/``script/output.txt`` onto its fixed base
    (see module docstring for what that base is and why).

    Args:
        project_dir: The active ``.in-reach`` folder, as returned by
            :func:`~in_reach.app.project.get_project_dir`.
        folder: The gametype project folder to compile.
        save: If ``True`` (the activity bar's "Apply"), writes the successfully-built variant to
            ``build/dist/<folder.name>.bin`` plus the ``build/*.autogenerated.json`` snapshots. If
            ``False`` (a dry-run/"verify"), every step below still runs (so compile errors are
            still reported) but nothing is written.

    Returns:
        A :class:`BuildResult` -- ``success`` is ``False`` (with ``failure``/compiler messages
        populated) if anything above failed; never raises for a normal, reportable failure (a
        missing/unreadable ``settings/`` file, a malformed/schema-invalid settings/script_settings/
        strings JSON, a Megalo compile error, a settings/strings apply error, or -- only when
        ``save`` is set -- a save error).
    """
    settings_dir = folder / new_project.SETTINGS_DIRNAME
    script_dir = folder / new_project.SCRIPT_DIRNAME
    settings_path = settings_dir / "settings.json"
    try:
        settings = load_game_settings(settings_path)
    except (OSError, ValueError) as exc:
        return BuildResult(success=False, failure=f"Failed to read {settings_path}: {exc}")

    rvt = get_rvt()
    init_gametype_bin = new_project.source_variant_path(project_dir, folder)
    if init_gametype_bin.is_file():
        # See module docstring for why this is preferred over the packaged blank whenever it
        # exists.
        variant = rvt.load(str(init_gametype_bin))
    else:
        blank_path = resolve_blank_variant(firefight=not settings.meta.is_multiplayer)
        variant = rvt.load(str(blank_path))

    mp = variant.multiplayer
    content_header = variant.content_header
    result = BuildResult(success=True)

    if mp is not None:
        script_path = script_dir / decompile.SCRIPT_FILENAME
        source = script_path.read_text(encoding="utf-8") if script_path.is_file() else ""
        compile_result = mp.compile_script(source)
        result.fatal_errors = _messages(compile_result.fatal_errors)
        result.errors = _messages(compile_result.errors)
        result.warnings = _messages(compile_result.warnings)
        result.notices = _messages(compile_result.notices)
        if not compile_result.success:
            result.success = False
            result.failure = "Megalo compile failed -- see .errors/.fatal_errors for details."
            return result

        # Order matters: the script must already be compiled (above) so its forge-label/
        # scripted-option/etc. counts exist before settings/script_settings reference them;
        # strings applies last so settings/strings.json's own multi-language text wins over
        # settings.json's single-language description_string (see settings_writer/strings_writer
        # docstrings for both).
        try:
            settings_writer.apply_multiplayer_settings(mp, content_header, settings.multiplayer.game_settings)
            settings_writer.apply_meta_header(mp, content_header, settings.meta.title, settings.meta.description)
            settings_writer.apply_script_settings(mp, settings.multiplayer.script_settings)
        except ValueError as exc:
            return BuildResult(success=False, failure=f"Failed to apply settings: {exc}")

        strings_path = settings_dir / "strings.json"
        try:
            strings_data = strings_io.load_strings(strings_path)
        except (OSError, ValueError) as exc:
            return BuildResult(success=False, failure=f"Failed to read {strings_path}: {exc}")
        try:
            string_warnings = strings_writer.apply_strings(mp, strings_data)
        except ValueError as exc:
            return BuildResult(success=False, failure=f"Failed to apply strings: {exc}")
        result.notices = result.notices + [BuildMessage(line=0, col=0, text=w) for w in string_warnings]
    else:
        settings_writer.apply_meta_header(None, content_header, settings.meta.title, settings.meta.description)

    if save:
        out_path = new_project.compiled_variant_path(folder)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            variant.save(str(out_path))
        except Exception as exc:  # noqa: BLE001 -- native save code can raise almost anything
            result.success = False
            result.failure = f"Compiled successfully but failed to save: {exc}"
            return result
        result.output_path = out_path

        category, category_icon = settings_io.load_meta_category(settings_path)
        title, description = settings_io.load_meta_title_description(settings_path)
        try:
            write_build_snapshot(
                variant,
                out_path,
                folder,
                category=category,
                category_icon=category_icon,
                title=title,
                description=description,
            )
        except Exception as exc:  # noqa: BLE001 -- extraction/pydantic code can raise almost anything
            result.success = False
            result.failure = f"Saved {out_path} but failed to write build/*.autogenerated.json: {exc}"
            return result

    return result
