"""Compiles a project's ``settings/`` (settings.json/script_settings.json/strings.json) and
``script/output.txt`` into a real game variant (PROMPT.md: "applying changes should try and
compile the jsons into a gametype and i[f] it fails then dont allow application (raise errors in
text window - although hopefully our schema validation should catch this)").

Ported/adapted from ``in-reach-v2``'s own ``app/compile.py::run_compile`` -- always rebuilds from a
fixed base, never mutates ``build/``'s own prior output incrementally: preferably this project's
own ``.in-reach/init_gametype/<id>.bin`` (see
:func:`~in_reach.app.new_project.source_variant_path` -- the packaged blank always has zero
forge-labels/scripted-options/player-traits-sets/HUD-widgets, and the Megalo compiler can't create
a slot in any of those tables just because a script references it by index -- only forge labels
self-vivify, by name, and only as a notice, not an error -- so a script that references any of the
others by index can only ever compile against a base that already has that many slots; loading
this project's own record of its original source ``.bin`` preserves that instead of starting from
zero every time), falling back to the packaged blank (multiplayer or Firefight, picked from
``settings/settings.json``'s own ``meta.is_multiplayer``, see
:mod:`in_reach.app.blank_variant`) only when that record is missing.

Unlike v2, this doesn't write a ``.mglo`` (RVT's own hot-reload-into-MCC format) -- that's a
separate feature (``inreach load``) this app has no equivalent of yet, not part of what PROMPT.md
asked for here.

A successful ``save=True`` run writes ``build/dist/<folder-name>.bin`` plus
``build/*.autogenerated.json`` -- the latter via :func:`~in_reach.app.rvt.decompile.
write_build_snapshot`, re-extracted from the just-compiled ``variant`` (not a copy of
``settings/``'s own input), so it reflects exactly what the compiler actually produced.

It also writes back into ``settings/script_settings.json`` and ``settings/strings.json``, but only
when the script created something they didn't list yet (or stopped needing something untouched they
did): the script decides how many forge labels and script strings a variant has -- naming a label
creates it, and ``settings/`` can't -- so :func:`~in_reach.app.rvt.settings_writer.
reconcile_forge_labels` and :func:`~in_reach.app.rvt.strings_writer.reconcile_script_strings` make the
two files follow the compiled variant before they're applied. Without the write-back the files would
list fewer entries than the snapshot above, and Apply would read "unapplied" forever. Nothing is
written for a dry run (``save=False``) or a failed compile.

The real work (:func:`_run_compile_in_process`, everything from :func:`~in_reach.app.rvt.
rvt_bridge.get_rvt` onward) runs in an isolated child process, spawned by the public
:func:`run_compile` -- never directly in whatever process called it. The bundled native
``_reachvarianttool`` extension (see ``rvt_bridge``) loads its own copy of Qt5 (``rvt/native/
Qt5Core.dll``); this app's own IDE loads PyQt6's Qt6. Two different major Qt versions coexisting in
one process is fundamentally unsupported, and confirmed (a real, native access-violation crash,
reproducible independent of PyQt6/Qt6 patch version, file type, or resize frequency -- everything
*except* whether the process had ever loaded ``_reachvarianttool``) to eventually corrupt Qt6's own
widget rendering later in that same process, well after the native module import itself returns
successfully. Isolating it in its own process, communicating back a plain :class:`BuildResult` over
a temp file (never stdout -- native code the extension calls into isn't guaranteed not to write to
it directly), contains the blast radius of that conflict entirely: even a hard crash in the child
(an access violation, same as before) now just fails that one compile with a reportable
:class:`BuildResult`, instead of taking the whole IDE down with it.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

from pydantic import BaseModel

from in_reach.app import logging_setup, new_project, script_preprocess
from in_reach.app.blank_variant import resolve_blank_variant

from . import decompile, megalo_compiler, settings_io, settings_writer, strings_io, strings_writer, template_source
from .decompile import write_build_snapshot
from .rvt_bridge import get_rvt
from .settings_io import load_game_settings

_logger = logging_setup.get_logger(__name__)


class BuildMessage(BaseModel):
    """One compiler/preprocessor message. ``line`` and ``col`` are both **1-based**, matching the
    editor's own Ln/Col; ``0``/``0`` means "no position" (a message about the build as a whole)."""

    line: int
    col: int
    text: str


class BuildResult(BaseModel):
    """``fatal_errors``/``errors``/``warnings``/``notices`` come straight from the Megalo compiler
    when a script was compiled (empty otherwise); ``failure`` holds a human-readable reason for
    anything the compiler log can't already explain (a missing/unreadable file, a settings-apply
    ``ValueError``, a save failure). Named ``Build*`` (not ``Compile*``) specifically to avoid
    confusion with the native ``_reachvarianttool.CompileMessage``/``CompileResult`` classes."""

    success: bool
    fatal_errors: list[BuildMessage] = []
    errors: list[BuildMessage] = []
    warnings: list[BuildMessage] = []
    notices: list[BuildMessage] = []
    failure: str | None = None
    output_path: Path | None = None


def _messages(items) -> list[BuildMessage]:
    """Native ``CompileMessage``s as :class:`BuildMessage`s. The native compiler numbers lines from
    **0** (a mistake on the first line reports line 0) but columns from 1, so its lines are shifted up
    by one here -- left as they were, every error pointed one line above the one that was wrong."""
    return [BuildMessage(line=m.line + 1, col=m.col, text=m.text) for m in items]


def format_build_result(result: BuildResult) -> str:
    """A single multi-line, user-facing message summarizing everything a failed (or
    warning-carrying) :class:`BuildResult` reported -- what the Apply button's own failure dialog
    shows (PROMPT.md: "raise errors in text window")."""
    lines: list[str] = []
    if result.failure:
        lines.append(result.failure)
    for label, messages in (
        ("fatal error", result.fatal_errors),
        ("error", result.errors),
        ("warning", result.warnings),
        ("notice", result.notices),
    ):
        for message in messages:
            lines.append(f"{label} ({message.line}:{message.col}): {message.text}")
    return "\n".join(lines)


def run_compile(project_dir: Path, folder: Path, *, save: bool) -> BuildResult:
    """Builds ``folder``'s project from ``settings/``/``script/output.txt`` onto its fixed base
    (see module docstring for what that base is and why, and for why the real work happens in an
    isolated child process rather than here).

    Args:
        project_dir: The active ``.in-reach`` folder, as returned by
            :func:`~in_reach.app.project.get_project_dir`.
        folder: The gametype project folder to compile.
        save: If ``True`` (the activity bar's "Apply"), writes the successfully-built variant to
            ``build/dist/<folder.name>.bin`` plus the ``build/*.autogenerated.json`` snapshots. If
            ``False`` (a dry-run/"verify"), every step below still runs (so compile errors are
            still reported) but nothing is written.

    Returns:
        A :class:`BuildResult` -- ``success`` is ``False`` (with ``failure``/compiler messages
        populated) if anything above failed; never raises for a normal, reportable failure (a
        missing/unreadable ``settings/`` file, a malformed/schema-invalid settings/script_settings/
        strings JSON, a Megalo compile error, a settings/strings apply error, a save error, or the
        isolated child process itself crashing).
    """
    # Validated here, in the caller's own process, before ever spawning a child for it -- a cheap,
    # extremely common failure (nothing to compile yet) shouldn't pay for a subprocess launch, and
    # a test asserting this path never touches the native extension at all should still be able to
    # (see test_run_compile_reports_unreadable_settings_json_without_touching_the_native_extension).
    settings_path = folder / new_project.SETTINGS_DIRNAME / "settings.json"
    try:
        load_game_settings(settings_path)
    except (OSError, ValueError) as exc:
        return BuildResult(success=False, failure=f"Failed to read {settings_path}: {exc}")

    return _run_compile_isolated(project_dir, folder, save=save)


def _run_compile_isolated(project_dir: Path, folder: Path, *, save: bool) -> BuildResult:
    """Runs :func:`_run_compile_in_process` in a fresh, isolated ``python -m`` child process (see
    this module's own docstring for why) -- everything from loading the native
    ``_reachvarianttool`` extension onward.

    The child writes its own :class:`BuildResult` as JSON to a temp file this passes it (never
    stdout: some native calls the extension makes print straight to the C stdout stream --
    :func:`~in_reach.app.rvt.rvt_bridge._suppress_native_stdout`'s own docstring already documents
    one such case -- and there's no guarantee every such write happens to be one this app already
    knows to suppress; a temp file sidesteps having to enumerate them all).

    A crash in the child (an access violation -- the exact failure mode this isolation exists to
    contain, see the module docstring) surfaces here as a non-zero/killed-by-signal return code,
    reported as an ordinary failed :class:`BuildResult` rather than propagating any further.
    """
    fd, result_path_str = tempfile.mkstemp(prefix="in-reach-compile-", suffix=".json")
    os.close(fd)
    result_path = Path(result_path_str)
    try:
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "in_reach.app.rvt.compile_subprocess",
                str(project_dir),
                str(folder),
                "1" if save else "0",
                str(result_path),
            ],
            capture_output=True,
            text=True,
            # CREATE_NO_WINDOW only exists on Windows -- see in_reach.app.halo_status's own
            # identical use of this for why a bare attribute access would break elsewhere.
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
        if proc.returncode != 0:
            _logger.error(
                "compile subprocess for %s exited with code %s: %s",
                folder,
                proc.returncode,
                (proc.stderr or proc.stdout).strip(),
            )
            return BuildResult(
                success=False,
                failure=(
                    f"The compile process exited unexpectedly (code {proc.returncode})."
                    f"{(' ' + proc.stderr.strip()) if proc.stderr.strip() else ''}"
                ),
            )
        try:
            return BuildResult.model_validate_json(result_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            _logger.exception("couldn't read compile subprocess result for %s", folder)
            return BuildResult(success=False, failure=f"Couldn't read the compile result: {exc}")
    finally:
        result_path.unlink(missing_ok=True)


def _preprocess_failure(exc: script_preprocess.PreprocessError) -> BuildResult:
    """A :class:`BuildResult` for a script or profile the preprocessor rejected. A problem in the script
    is reported like any compiler error (with its line and column, which preprocessing never shifts); one
    in an env file names that file, since its line numbers mean nothing to the script's editor."""
    if exc.path is None:
        return BuildResult(
            success=False,
            errors=[BuildMessage(line=exc.line, col=exc.col + 1, text=exc.message)],  # col: 0- -> 1-based
            failure="The script couldn't be preprocessed -- see the errors.",
        )
    return BuildResult(success=False, failure=f"{exc.path.name}, line {exc.line}: {exc.message}")


def _run_compile_in_process(project_dir: Path, folder: Path, *, save: bool) -> BuildResult:
    """The real compile work -- only ever called from :mod:`in_reach.app.rvt.compile_subprocess`,
    inside the isolated child process :func:`_run_compile_isolated` spawns. Never call this
    directly from the GUI process -- see this module's own docstring for why.
    """
    settings_dir = folder / new_project.SETTINGS_DIRNAME
    script_dir = folder / new_project.SCRIPT_DIRNAME
    settings_path = settings_dir / "settings.json"
    try:
        settings = load_game_settings(settings_path)
    except (OSError, ValueError) as exc:
        return BuildResult(success=False, failure=f"Failed to read {settings_path}: {exc}")

    rvt = get_rvt()
    init_gametype_bin = new_project.source_variant_path(project_dir, folder)
    if init_gametype_bin.is_file():
        # See module docstring for why this is preferred over the packaged blank whenever it
        # exists.
        variant_source_path = init_gametype_bin
    else:
        variant_source_path = resolve_blank_variant(firefight=not settings.meta.is_multiplayer)
    variant = rvt.load(str(variant_source_path))

    mp = variant.multiplayer
    content_header = variant.content_header
    result = BuildResult(success=True)

    if mp is not None:
        script_path = script_dir / decompile.SCRIPT_FILENAME
        raw_source = script_path.read_text(encoding="utf-8") if script_path.is_file() else ""
        # Apply the active environment profile (its ${CONSTANTS} and -- @if blocks) *first*: everything
        # below -- the unchanged-since-decompile check, the in-house compiler, the native fallback -- must
        # see the text that's actually being built, not the source with its directives still in.
        try:
            source = script_preprocess.preprocess_project(folder, raw_source)
        except script_preprocess.PreprocessError as exc:
            return _preprocess_failure(exc)
        # PROMPT.md: "we want to make sure when we compile or decompile a script it processes the
        # code correctly ... i want a working compiler/decompiler we can rely on" -- confirmed by
        # direct testing that mp.compile_script() is not a stable fixed point over its own
        # decompile_script() output: recompiling the juggernaut fixture completely unedited changes
        # 25 triggers/92 actions to 19/91 (a real, reproducible discrepancy, not a guess -- some
        # ordinary nested-trigger blocks silently recompile as "inline" triggers instead, a
        # non-configurable default the native compiler makes on its own -- see
        # in_reach.app.rvt.megalo_compiler's own module docstring for the root cause and for the
        # real, from-scratch compiler this reaches for below). `variant` was just loaded straight
        # from init_gametype_bin, so its own script bytecode is already exactly correct -- if
        # `source` hasn't actually changed since it was decompiled from this same base, skip
        # recompiling it at all rather than re-deriving bytecode that's already sitting right there
        # and risking a discrepancy like the one above for zero reason.
        if source == decompile.normalize_script_text(variant.decompile_script()):
            _logger.info(
                "script unchanged since decompile for %s -- skipping recompile to avoid the "
                "non-idempotent decompile/recompile round trip",
                folder,
            )
        else:
            fallback_reason = None
            try:
                # The synthetic template pool is only built if the script needs something this base
                # variant's own script can't supply -- see megalo_compiler.compile_script().
                megalo_compiler.compile_script(
                    rvt, variant, source, template_pool=lambda: template_source.build_variants(rvt)
                )
                # A successful compile_script() call isn't, on its own, proof that `variant` is
                # actually a valid, reloadable game variant -- confirmed real, if rare, cases: a
                # script that exceeds Megalo::Limits::max_actions/max_conditions used to save()
                # without error yet fail to load() back -- megalo_compiler.py's own compile() now
                # checks that proactively (see its own module docstring), so this probe usually isn't
                # what catches that specific case any more. Two more native round-trip bugs this probe
                # used to be the only defense against (see megalo_compiler's own "Fixed: two distinct
                # native round-trip bugs" section) are now fixed at the source -- but this probe stays
                # as defense in depth regardless. Verifying the actual round trip here -- before this
                # compile is ever trusted -- is what PROMPT.md's own "I want a working compiler/
                # decompiler we can rely on" requires: never ship a build neither this app nor the game
                # itself can load back, silently, for *any* reason, including ones not yet discovered.
                probe_fd, probe_path_str = tempfile.mkstemp(suffix=".bin")
                os.close(probe_fd)  # mkstemp's own fd must be closed before anything else opens this
                # path on Windows, or save()/load() below (and the unlink() in `finally`) can fail
                # with a spurious WinError 32 "used by another process" -- confirmed a real bug,
                # caught by this very verification: an open handle on `probe_path` its own self
                # leaked here once made every compile through this path fall back to the native
                # compiler unconditionally, regardless of whether the actual compile was fine.
                probe_path = Path(probe_path_str)
                try:
                    variant.save(str(probe_path))
                    rvt.load(str(probe_path))
                except Exception as exc:  # noqa: BLE001 -- any failure here means "don't trust this build"
                    fallback_reason = f"compiled build failed its own save/reload verification: {exc}"
                finally:
                    probe_path.unlink(missing_ok=True)
            except megalo_compiler.UnsupportedConstruct as exc:
                fallback_reason = f"megalo_compiler doesn't cover this script yet: {exc}"
            except Exception as exc:  # noqa: BLE001 -- an unexpected native-layer failure, not a
                # recognized "outside this compiler's supported subset" case -- still falls back
                # rather than taking the whole compile down, but logged distinctly (warning, not
                # info) since this represents a real bug in megalo_compiler.py or its native
                # bindings worth investigating, not an expected/understood gap.
                _logger.warning(
                    "megalo_compiler hit an unexpected error compiling %s -- falling back to the "
                    "native compiler: %s",
                    folder,
                    exc,
                    exc_info=True,
                )
                fallback_reason = f"unexpected megalo_compiler error: {exc}"

            if fallback_reason is not None:
                _logger.info(
                    "%s -- falling back to the native compiler for %s",
                    fallback_reason,
                    folder,
                )
                # megalo_compiler may have already appended partially-built triggers before hitting
                # the unsupported construct, and MultiplayerData has no way to remove/undo those --
                # see its own module docstring. A genuinely fresh variant is the only safe recovery.
                variant = rvt.load(str(variant_source_path))
                mp = variant.multiplayer
                content_header = variant.content_header
                compile_result = mp.compile_script(source)
                result.fatal_errors = _messages(compile_result.fatal_errors)
                result.errors = _messages(compile_result.errors)
                result.warnings = _messages(compile_result.warnings)
                result.notices = _messages(compile_result.notices)
                if not compile_result.success:
                    result.success = False
                    result.failure = "Megalo compile failed -- see .errors/.fatal_errors for details."
                    return result

        # Order matters: the script must already be compiled (above) so its forge-label/
        # scripted-option/etc. counts exist before settings/script_settings reference them;
        # strings applies last so settings/strings.json's own multi-language text wins over
        # settings.json's single-language description_string (see settings_writer/strings_writer
        # docstrings for both).
        try:
            # The script decides how many forge labels exist (naming one creates it), so settings/
            # has to follow the compiled variant, not the other way round -- see
            # settings_writer.reconcile_forge_labels()'s docstring.
            reconciled = settings_writer.reconcile_forge_labels(
                rvt, mp, settings.multiplayer.script_settings, settings.multiplayer.game_settings.team_settings.teams
            )
            # The four other script-defined tables (options, traits, stats, widgets) can be created
            # from either side, so this grows the variant to match settings as well as the reverse.
            # It has to come *before* anything from settings/ is applied: creating an option resets
            # that option's own "disabled"/"hidden" visibility bits, so growing the variant after
            # apply_multiplayer_settings() had set them silently undid what settings.json said.
            tables = settings_writer.reconcile_script_tables(rvt, mp, reconciled.script_settings)
            settings_writer.apply_multiplayer_settings(mp, content_header, settings.multiplayer.game_settings)
            settings_writer.apply_meta_header(mp, content_header, settings.meta.title, settings.meta.description)
            settings_writer.apply_script_settings(mp, tables.script_settings)
        except ValueError as exc:
            return BuildResult(success=False, failure=f"Failed to apply settings: {exc}")
        if reconciled.added:
            result.notices.append(
                BuildMessage(line=0, col=0, text=f"Added forge label(s) to script_settings.json: {', '.join(reconciled.added)}")
            )
        if reconciled.removed:
            result.notices.append(
                BuildMessage(line=0, col=0, text=f"Removed unused forge label(s) from script_settings.json: {', '.join(reconciled.removed)}")
            )
        for table_field, how_many in tables.added.items():
            result.notices.append(
                BuildMessage(line=0, col=0, text=f"Added {how_many} {table_field} entr{'y' if how_many == 1 else 'ies'} to script_settings.json")
            )

        strings_path = settings_dir / "strings.json"
        try:
            strings_data = strings_io.load_strings(strings_path)
        except (OSError, ValueError) as exc:
            return BuildResult(success=False, failure=f"Failed to read {strings_path}: {exc}")
        # Same idea as the forge labels above: the script decides which strings exist.
        reconciled_strings = strings_writer.reconcile_script_strings(mp, strings_data)
        try:
            string_warnings = strings_writer.apply_strings(mp, reconciled_strings.strings)
        except ValueError as exc:
            return BuildResult(success=False, failure=f"Failed to apply strings: {exc}")
        result.notices = result.notices + [BuildMessage(line=0, col=0, text=w) for w in string_warnings]
        if reconciled_strings.added:
            result.notices.append(
                BuildMessage(line=0, col=0, text=f"Added {len(reconciled_strings.added)} script string(s) to strings.json")
            )
        if reconciled_strings.removed:
            result.notices.append(
                BuildMessage(line=0, col=0, text=f"Removed {len(reconciled_strings.removed)} unused script string(s) from strings.json")
            )
    else:
        reconciled = tables = reconciled_strings = None
        settings_writer.apply_meta_header(None, content_header, settings.meta.title, settings.meta.description)
        ff = variant.firefight
        if ff is not None and settings.firefight is not None:
            try:
                settings_writer.apply_firefight_settings(ff, settings.firefight)
            except ValueError as exc:
                return BuildResult(success=False, failure=f"Failed to apply settings: {exc}")

    if save:
        out_path = new_project.compiled_variant_path(folder)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            variant.save(str(out_path))
        except Exception as exc:  # noqa: BLE001 -- native save code can raise almost anything
            result.success = False
            result.failure = f"Compiled successfully but failed to save: {exc}"
            return result
        result.output_path = out_path

        # Only now -- the build succeeded and saved -- is it safe to change a file the user owns.
        # (Without this write the Apply button would read "unapplied" forever: settings/ would list
        # fewer labels than the build snapshot re-extracted just below.)
        schema_dir = folder / new_project.SCHEMA_DIRNAME
        script_settings_path = settings_dir / decompile.SCRIPT_SETTINGS_FILENAME
        strings_path = settings_dir / decompile.STRINGS_FILENAME
        try:
            if reconciled is not None and (reconciled.changed or tables.changed):
                schema = schema_dir / decompile.SCRIPT_SETTINGS_SCHEMA_FILENAME
                settings_io.dump_script_settings(
                    tables.script_settings, script_settings_path, schema if schema.is_file() else None
                )
            if reconciled_strings is not None and reconciled_strings.changed:
                schema = schema_dir / decompile.STRINGS_SCHEMA_FILENAME
                strings_io.write_strings_json(
                    reconciled_strings.strings, strings_path, schema if schema.is_file() else None
                )
        except OSError as exc:
            result.success = False
            result.failure = f"Compiled successfully but failed to update settings/: {exc}"
            return result

        category, category_icon = settings_io.load_meta_category(settings_path)
        title, description = settings_io.load_meta_title_description(settings_path)
        created_at = settings_io.load_meta_generated_at(settings_path)
        try:
            write_build_snapshot(
                variant,
                out_path,
                folder,
                category=category,
                category_icon=category_icon,
                title=title,
                description=description,
                created_at=created_at,
            )
        except Exception as exc:  # noqa: BLE001 -- extraction/pydantic code can raise almost anything
            result.success = False
            result.failure = f"Saved {out_path} but failed to write build/*.autogenerated.json: {exc}"
            return result

    return result
