"""Decompiles a source ``.bin`` into a project's ``settings/`` (a live mirror) and ``build/`` (a
disposable ``*.autogenerated.json`` snapshot of the same data), and seeds ``script/game.txt`` --
the one part of this that's never touched again after the first decompile.

The ``in-reach-v1``/``in-reach-v2`` prototypes did this as part of their own ``init`` command --
see :mod:`in_reach.app.new_project`'s module docstring for why it was left out of this repo's
first pass (the native ``_reachvarianttool`` extension wasn't ported yet). Now that it is (see
:mod:`in_reach.app.rvt.rvt_bridge`), :func:`decompile_into_project` is the thin wrapper that
replaces v1's own ``project_io.write_project_files`` for this repo's folder naming (v1 used
``cfg/``/``dist/``) -- settings/strings/build-stats extracted as validated JSON via
:mod:`in_reach.app.rvt.extraction`/``build_stats``/``settings_io``/``strings_io``, and the Megalo
script itself via the native module's own ``decompile_script()`` (no AST reimplementation needed).

PROMPT.md: "we should have .generated.json files be created when the project is started and they
should update when rvt saves" -- :func:`decompile_into_project` (project creation) writes
``script/game.txt``, ``settings/`` and the matching ``build/*.autogenerated.json`` snapshot from
the same decompile pass; :func:`resync_from_bin` re-writes just ``settings/``/``build/`` later, on
its own, for ``MainWindow``'s own ``.bin``-file-watcher to call whenever RVT saves over the source
``.bin`` out from under a running project -- ``script/game.txt`` is deliberately never touched by
that resync, since it's the one genuinely hand-editable thing here, not a live mirror of the
``.bin`` the way everything else now is.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from in_reach.app import maps_io, new_project
from in_reach.app.categories import EngineCategory, EngineIcon

from . import schema_io, settings_io, strings_io
from .build_stats import build_stats_from_multiplayer
from .extraction import extract_game_settings
from .models.build_stats import BuildStats
from .models.game_settings import GameSettings
from .models.script_settings import ScriptSettings
from .models.strings import StringsDocument
from .rvt_bridge import get_rvt

SETTINGS_FILENAME = "settings.json"
SCRIPT_SETTINGS_FILENAME = "script_settings.json"
STRINGS_FILENAME = "strings.json"
SCRIPT_FILENAME = "game.txt"  # PROMPT.md: "move script.txt to be script/game.txt"

GENERATED_SETTINGS_FILENAME = "settings.autogenerated.json"
GENERATED_SCRIPT_SETTINGS_FILENAME = "script_settings.autogenerated.json"
GENERATED_STRINGS_FILENAME = "strings.autogenerated.json"
GENERATED_STATS_FILENAME = "stats.autogenerated.json"

# PROMPT.md: "in settings, please not[e] examples from repo v2 ... where we have a schema, please
# re-add this to the top of the files" -- JSON Schema files for settings/'s own JSON, regenerated
# fresh from the live Pydantic models on every decompile/resync, same as v2's own convention (see
# schema_io.py's docstring). PROMPT.md later: "move settings/schemas into schemas" -- a project-root
# folder of their own (see :data:`~in_reach.app.new_project.SCHEMA_DIRNAME`), not nested under
# settings/, since they document settings/'s JSON shape without being one of its own files. build/'s
# own snapshot doesn't get any -- it's disposable, autogenerated output no editor tooling needs to
# validate against.
SETTINGS_SCHEMA_FILENAME = "settings.schema.json"
SCRIPT_SETTINGS_SCHEMA_FILENAME = "script_settings.schema.json"
STRINGS_SCHEMA_FILENAME = "strings.schema.json"


@dataclass
class _Decompiled:
    game_settings: GameSettings
    script_settings: ScriptSettings
    strings: dict
    script_text: str
    stats: BuildStats | None  # only ever present for a multiplayer variant


def _build_decompiled(
    variant,
    source_path: Path,
    *,
    category: EngineCategory,
    category_icon: EngineIcon | None,
    title: str | None = None,
    description: str | None = None,
) -> _Decompiled:
    """The shared second half of :func:`_decompile` (loads-then-builds) and
    :func:`write_build_snapshot` (already-loaded/compiled-then-builds) -- everything that turns an
    in-memory ``variant`` into the plain extracted shape :func:`_write_generated_files` writes."""
    game_settings = extract_game_settings(variant, source_path)
    game_settings.meta.category = category
    game_settings.meta.category_icon = category_icon
    # PROMPT.md: "when setting a title and description, this is not being set in settings.json" --
    # at creation time (decompile_into_project) and after a real compile (write_build_snapshot),
    # this project's own title/description (the New Project dialog's, or a hand-edited
    # settings.json's) should override whatever the source .bin's own header carries, same
    # override-with-this-project's-own-value reasoning as category/category_icon above.
    #
    # ``None`` (rather than these two ever defaulting to a blank string) means "no override" --
    # resync_from_bin (RVT saving over the .bin out from under an already-decompiled project) is the
    # one caller that passes neither, specifically so a rename typed straight into RVT's own header
    # field flows through here too (PROMPT.md: "when a project name is changed via rvt ... the
    # project title should change in the tabs and in the breadcrumb"), rather than being silently
    # reverted back to whatever settings.json said before this save. Meta.description has a real,
    # engine-derived max_length (127) shorter than the New Project dialog's own
    # (MAX_DESCRIPTION_LENGTH, 137) -- truncated here rather than raising, since a decompile
    # shouldn't fail over a few characters this field was never going to keep anyway.
    if title is not None:
        game_settings.meta.title = title
    if description is not None:
        game_settings.meta.description = description[:127]
    script_settings = (
        game_settings.multiplayer.script_settings
        if game_settings.multiplayer is not None
        else ScriptSettings()
    )
    strings = strings_io.extract_strings(variant.multiplayer)
    stats = build_stats_from_multiplayer(variant.multiplayer) if variant.multiplayer is not None else None
    return _Decompiled(game_settings, script_settings, strings, variant.decompile_script(), stats)


def _decompile(
    bin_path: Path,
    *,
    category: EngineCategory,
    category_icon: EngineIcon | None,
    title: str | None = None,
    description: str | None = None,
) -> _Decompiled:
    rvt = get_rvt()
    variant = rvt.load(str(bin_path))
    return _build_decompiled(
        variant, bin_path, category=category, category_icon=category_icon, title=title, description=description
    )


def write_build_snapshot(
    variant,
    out_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    title: str | None = None,
    description: str | None = None,
) -> None:
    """Extracts from an already-loaded/compiled ``variant`` (see
    :mod:`in_reach.app.rvt.compile`'s ``run_compile()``) and writes *only*
    ``folder``'s ``build/*.autogenerated.json`` snapshot -- never ``settings/``, unlike
    :func:`decompile_into_project`/:func:`resync_from_bin` above. A real compile's own
    ``build/`` snapshot should reflect exactly what the compiler actually produced (echoing
    back its own normalization), not a second re-decompile of ``settings/`` that could silently
    diverge from what got baked into the ``.bin``; hand-edited ``settings/`` stays exactly what
    the user wrote, untouched by a successful Apply.

    Args:
        variant: The just-compiled ``GameVariant`` (already ``.save()``d to ``out_path``).
        out_path: Where ``variant`` was just saved -- used as this snapshot's own
            ``meta.source_file``.
        folder: The gametype project folder whose ``build/`` to write into.
        category/category_icon/title/description: This project's own values, same as
            :func:`decompile_into_project` -- callers should read these back from
            ``settings/settings.json`` (see
            :func:`~in_reach.app.rvt.settings_io.load_meta_category`/``load_meta_title_description``)
            rather than losing them.
    """
    decompiled = _build_decompiled(
        variant, out_path, category=category, category_icon=category_icon, title=title, description=description
    )
    _write_generated_files(
        decompiled,
        folder / new_project.BUILD_DIRNAME,
        GENERATED_SETTINGS_FILENAME,
        GENERATED_SCRIPT_SETTINGS_FILENAME,
        GENERATED_STRINGS_FILENAME,
        stats_filename=GENERATED_STATS_FILENAME,
    )


def decompile_into_project(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    title: str | None = None,
    description: str | None = None,
    map_entries: list[maps_io.MapEntry] = (),
) -> None:
    """Loads ``bin_path`` through the bundled ReachVariantTool extension and writes what it decodes
    into ``folder``'s ``settings/`` (settings/script settings/strings/valid maps, as JSON) and
    ``edit/rvt/`` (the decompiled Megalo script, as plain text) -- plus, per PROMPT.md, the matching
    ``build/*.autogenerated.json`` snapshot (see :func:`_write_generated_files`), so a
    freshly-created project already has both halves rather than an empty ``build/`` until the next
    RVT save.

    Args:
        bin_path: The source ``.bin`` to decompile -- normally
            :func:`~in_reach.app.new_project.source_variant_path`'s result for ``folder``.
        folder: The gametype project folder to write into, as returned by
            :func:`~in_reach.app.new_project.create_gametype_project`.
        category: This project's own :class:`~in_reach.app.categories.EngineCategory` (PROMPT.md:
            "move category and category_icon into settings.json") -- independent of whatever the
            source ``.bin`` itself carries as its engine-level category (see
            ``Meta.category``'s own docstring).
        category_icon: This project's own :class:`~in_reach.app.categories.EngineIcon`.
        title: This project's own title (PROMPT.md: "when setting a title and description, this
            is not being set in settings.json") -- stamped into ``meta.title``, overriding whatever
            title the source ``.bin`` itself carries in its own header.
        description: This project's own description, stamped into ``meta.description`` the same
            way (truncated to fit that field's own, shorter, engine-derived length limit).
        map_entries: The shared ``.in-reach/maps.json`` scan (see
            :func:`~in_reach.app.maps_io.scan_maps`), narrowed down into ``settings/valid_maps.json``
            via :func:`~in_reach.app.maps_io.filter_maps_for_gametype`.

    Raises:
        Whatever the native extension or pydantic validation raises for a ``.bin`` it can't load or
        make sense of -- callers decide whether that should block project creation or just surface
        as a warning (see that function's own handling).
    """
    decompiled = _decompile(
        bin_path, category=category, category_icon=category_icon, title=title, description=description
    )

    script_dir = folder / new_project.SCRIPT_DIRNAME
    script_dir.mkdir(parents=True, exist_ok=True)
    (script_dir / SCRIPT_FILENAME).write_text(decompiled.script_text, encoding="utf-8")

    _write_generated_files(
        decompiled,
        folder / new_project.SETTINGS_DIRNAME,
        SETTINGS_FILENAME,
        SCRIPT_SETTINGS_FILENAME,
        STRINGS_FILENAME,
        write_schema=True,
        folder=folder,
    )
    _write_generated_files(
        decompiled,
        folder / new_project.BUILD_DIRNAME,
        GENERATED_SETTINGS_FILENAME,
        GENERATED_SCRIPT_SETTINGS_FILENAME,
        GENERATED_STRINGS_FILENAME,
        stats_filename=GENERATED_STATS_FILENAME,
        # PROMPT.md: "move settings/valid_maps.json to build/valid_maps.json".
        map_entries=map_entries,
    )


def resync_from_bin(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    title: str | None = None,
    description: str | None = None,
    map_entries: list[maps_io.MapEntry] = (),
) -> None:
    """Re-decompiles ``bin_path`` and rewrites ``folder``'s ``settings/`` and
    ``build/*.autogenerated.json`` snapshot -- PROMPT.md: "[generated files] should update when
    rvt saves". ``edit/rvt/script.txt`` is left completely alone: this is meant to be called
    whenever the *source* ``.bin`` changes out from under an already-decompiled project (RVT saving
    over it), not at project creation, and that script is the one genuinely hand-editable thing
    here, never auto-overwritten once seeded.

    Args:
        bin_path: The ``.bin`` that just changed.
        folder: The gametype project folder to resync.
        category/category_icon: This project's own classification, same as
            :func:`decompile_into_project` -- callers should read these back from the project's
            existing ``settings/settings.json`` (see
            :func:`~in_reach.app.rvt.settings_io.load_meta_category`) rather than losing them on
            every resync -- unlike title/description below, a project's category isn't something
            the ``.bin`` itself has any concept of at all, so there's nothing for a resync to ever
            pick up *from* it.
        title/description: Left ``None`` by every real caller (the ``.bin``-file-watcher) on
            purpose -- PROMPT.md: "when a project name is changed via rvt ... the project title
            should change in the tabs and in the breadcrumb". Passing an explicit override here
            would silently revert a rename typed straight into RVT's own header field back to
            whatever ``settings.json`` said before this save; leaving both ``None`` instead lets
            the freshly-extracted values from ``bin_path`` itself flow straight into
            ``settings/settings.json`` (and, from there, into the project's README -- see
            :func:`~in_reach.app.new_project.set_project_title` -- and every UI that reads
            :func:`~in_reach.app.new_project.read_project_title`). Still accepted as real overrides
            for anything that *does* want one (see ``test_resync_from_bin_carries_title_and_
            description_through``).
        map_entries: Same as :func:`decompile_into_project` -- callers should read this back from
            ``.in-reach/maps.json`` (see :func:`~in_reach.app.maps_io.read_maps_json`) rather than
            re-scanning the map-variant folders on every resync.

    Raises:
        Same as :func:`decompile_into_project` -- callers watching for RVT saves should treat this
        as best-effort and not let it crash the whole app over a ``.bin`` RVT left mid-write.
    """
    decompiled = _decompile(
        bin_path, category=category, category_icon=category_icon, title=title, description=description
    )
    _write_generated_files(
        decompiled,
        folder / new_project.SETTINGS_DIRNAME,
        SETTINGS_FILENAME,
        SCRIPT_SETTINGS_FILENAME,
        STRINGS_FILENAME,
        write_schema=True,
        folder=folder,
    )
    _write_generated_files(
        decompiled,
        folder / new_project.BUILD_DIRNAME,
        GENERATED_SETTINGS_FILENAME,
        GENERATED_SCRIPT_SETTINGS_FILENAME,
        GENERATED_STRINGS_FILENAME,
        stats_filename=GENERATED_STATS_FILENAME,
        map_entries=map_entries,
    )


def _write_generated_files(
    decompiled: _Decompiled,
    out_dir: Path,
    settings_filename: str,
    script_settings_filename: str,
    strings_filename: str,
    *,
    stats_filename: str | None = None,
    map_entries: list[maps_io.MapEntry] | None = None,
    write_schema: bool = False,
    folder: Path | None = None,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    settings_schema_path = script_settings_schema_path = strings_schema_path = None
    if write_schema:
        # PROMPT.md: "move settings/schemas into schemas" -- a project-root schemas/ (folder, not
        # out_dir -- the caller passing write_schema=True is always settings/'s own call, but the
        # schema files themselves no longer live inside settings/ at all).
        schema_dir = folder / new_project.SCHEMA_DIRNAME
        settings_schema_path = schema_io.dump_json_schema(GameSettings, schema_dir / SETTINGS_SCHEMA_FILENAME)
        script_settings_schema_path = schema_io.dump_json_schema(
            ScriptSettings, schema_dir / SCRIPT_SETTINGS_SCHEMA_FILENAME
        )
        strings_schema_path = schema_io.dump_json_schema(StringsDocument, schema_dir / STRINGS_SCHEMA_FILENAME)

    settings_io.dump_game_settings(decompiled.game_settings, out_dir / settings_filename, settings_schema_path)
    settings_io.dump_script_settings(
        decompiled.script_settings, out_dir / script_settings_filename, script_settings_schema_path
    )
    strings_io.write_strings_json(decompiled.strings, out_dir / strings_filename, strings_schema_path)
    if stats_filename is not None and decompiled.stats is not None:
        settings_io.dump_build_stats(decompiled.stats, out_dir / stats_filename)
    # None (settings/'s own call, above) means "not applicable here at all" -- PROMPT.md: "move
    # settings/valid_maps.json to build/valid_maps.json", so only build/'s own call ever passes
    # this now. Distinct from an empty list (a genuinely empty map scan), which still writes a real
    # (empty) valid_maps.json for consistency with the other three files.
    if map_entries is not None:
        valid_maps = maps_io.filter_maps_for_gametype(list(map_entries), decompiled.script_settings)
        maps_io.write_valid_maps_json(valid_maps, out_dir / maps_io.VALID_MAPS_FILENAME)
