"""Decompiles a source ``.bin`` into a project's ``settings/`` (a live mirror) and ``build/`` (a
disposable ``*.autogenerated.json`` snapshot of the same data), and seeds ``edit/rvt/script.txt``
-- the one part of this that's never touched again after the first decompile.

The ``in-reach-v1``/``in-reach-v2`` prototypes did this as part of their own ``init`` command --
see :mod:`in_reach.app.new_project`'s module docstring for why it was left out of this repo's
first pass (the native ``_reachvarianttool`` extension wasn't ported yet). Now that it is (see
:mod:`in_reach.app.rvt.rvt_bridge`), :func:`decompile_into_project` is the thin wrapper that
replaces v1's own ``project_io.write_project_files`` for this repo's folder naming (v1 used
``cfg/``/``dist/``) -- settings/strings/build-stats extracted as validated JSON via
:mod:`in_reach.app.rvt.extraction`/``build_stats``/``settings_io``/``strings_io``, and the Megalo
script itself via the native module's own ``decompile_script()`` (no AST reimplementation needed).

PROMPT.md: "we should have .generated.json files be created when the project is started and they
should update when rvt saves" -- :func:`decompile_into_project` (project creation) writes
``edit/rvt/script.txt``, ``settings/`` and the matching ``build/*.autogenerated.json`` snapshot
from the same decompile pass; :func:`resync_from_bin` re-writes just ``settings/``/``build/`` later,
on its own, for ``MainWindow``'s own ``.bin``-file-watcher to call whenever RVT saves over the
source ``.bin`` out from under a running project -- ``edit/rvt/script.txt`` is deliberately never
touched by that resync, since it's the one genuinely hand-editable thing here, not a live mirror of
the ``.bin`` the way everything else now is.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from in_reach.app import maps_io, new_project
from in_reach.app.categories import EngineCategory, EngineIcon

from . import settings_io, strings_io
from .build_stats import build_stats_from_multiplayer
from .extraction import extract_game_settings
from .models.build_stats import BuildStats
from .models.game_settings import GameSettings
from .models.script_settings import ScriptSettings
from .rvt_bridge import get_rvt

SETTINGS_FILENAME = "settings.json"
SCRIPT_SETTINGS_FILENAME = "script_settings.json"
STRINGS_FILENAME = "strings.json"
SCRIPT_FILENAME = "script.txt"

GENERATED_SETTINGS_FILENAME = "settings.autogenerated.json"
GENERATED_SCRIPT_SETTINGS_FILENAME = "script_settings.autogenerated.json"
GENERATED_STRINGS_FILENAME = "strings.autogenerated.json"
GENERATED_STATS_FILENAME = "stats.autogenerated.json"


@dataclass
class _Decompiled:
    game_settings: GameSettings
    script_settings: ScriptSettings
    strings: dict
    script_text: str
    stats: BuildStats | None  # only ever present for a multiplayer variant


def _decompile(
    bin_path: Path, *, category: EngineCategory, category_icon: EngineIcon | None
) -> _Decompiled:
    rvt = get_rvt()
    variant = rvt.load(str(bin_path))

    game_settings = extract_game_settings(variant, bin_path)
    game_settings.meta.category = category
    game_settings.meta.category_icon = category_icon
    script_settings = (
        game_settings.multiplayer.script_settings
        if game_settings.multiplayer is not None
        else ScriptSettings()
    )
    strings = strings_io.extract_strings(variant.multiplayer)
    stats = build_stats_from_multiplayer(variant.multiplayer) if variant.multiplayer is not None else None
    return _Decompiled(game_settings, script_settings, strings, variant.decompile_script(), stats)


def decompile_into_project(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    map_entries: list[maps_io.MapEntry] = (),
) -> None:
    """Loads ``bin_path`` through the bundled ReachVariantTool extension and writes what it decodes
    into ``folder``'s ``settings/`` (settings/script settings/strings/valid maps, as JSON) and
    ``edit/rvt/`` (the decompiled Megalo script, as plain text) -- plus, per PROMPT.md, the matching
    ``build/*.autogenerated.json`` snapshot (see :func:`_write_generated_files`), so a
    freshly-created project already has both halves rather than an empty ``build/`` until the next
    RVT save.

    Args:
        bin_path: The source ``.bin`` to decompile -- normally
            :func:`~in_reach.app.new_project.source_variant_path`'s result for ``folder``.
        folder: The gametype project folder to write into, as returned by
            :func:`~in_reach.app.new_project.create_gametype_project`.
        category: This project's own :class:`~in_reach.app.categories.EngineCategory` (PROMPT.md:
            "move category and category_icon into settings.json") -- independent of whatever the
            source ``.bin`` itself carries as its engine-level category (see
            ``Meta.category``'s own docstring).
        category_icon: This project's own :class:`~in_reach.app.categories.EngineIcon`.
        map_entries: The shared ``.in-reach/maps.json`` scan (see
            :func:`~in_reach.app.maps_io.scan_maps`), narrowed down into ``settings/valid_maps.json``
            via :func:`~in_reach.app.maps_io.filter_maps_for_gametype`.

    Raises:
        Whatever the native extension or pydantic validation raises for a ``.bin`` it can't load or
        make sense of -- callers decide whether that should block project creation or just surface
        as a warning (see that function's own handling).
    """
    decompiled = _decompile(bin_path, category=category, category_icon=category_icon)

    rvt_dir = folder / new_project.EDIT_DIRNAME / new_project.EDIT_RVT_SUBDIR
    rvt_dir.mkdir(parents=True, exist_ok=True)
    (rvt_dir / SCRIPT_FILENAME).write_text(decompiled.script_text, encoding="utf-8")

    _write_generated_files(
        decompiled,
        folder / new_project.SETTINGS_DIRNAME,
        SETTINGS_FILENAME,
        SCRIPT_SETTINGS_FILENAME,
        STRINGS_FILENAME,
        map_entries=map_entries,
    )
    _write_generated_files(
        decompiled,
        folder / new_project.BUILD_DIRNAME,
        GENERATED_SETTINGS_FILENAME,
        GENERATED_SCRIPT_SETTINGS_FILENAME,
        GENERATED_STRINGS_FILENAME,
        stats_filename=GENERATED_STATS_FILENAME,
    )


def resync_from_bin(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    map_entries: list[maps_io.MapEntry] = (),
) -> None:
    """Re-decompiles ``bin_path`` and rewrites ``folder``'s ``settings/`` and
    ``build/*.autogenerated.json`` snapshot -- PROMPT.md: "[generated files] should update when
    rvt saves". ``edit/rvt/script.txt`` is left completely alone: this is meant to be called
    whenever the *source* ``.bin`` changes out from under an already-decompiled project (RVT saving
    over it), not at project creation, and that script is the one genuinely hand-editable thing
    here, never auto-overwritten once seeded.

    Args:
        bin_path: The ``.bin`` that just changed.
        folder: The gametype project folder to resync.
        category/category_icon: This project's own classification, same as
            :func:`decompile_into_project` -- callers should read these back from the project's
            existing ``settings/settings.json`` (see
            :func:`~in_reach.app.rvt.settings_io.load_meta_category`) rather than losing them on
            every resync.
        map_entries: Same as :func:`decompile_into_project` -- callers should read this back from
            ``.in-reach/maps.json`` (see :func:`~in_reach.app.maps_io.read_maps_json`) rather than
            re-scanning the map-variant folders on every resync.

    Raises:
        Same as :func:`decompile_into_project` -- callers watching for RVT saves should treat this
        as best-effort and not let it crash the whole app over a ``.bin`` RVT left mid-write.
    """
    decompiled = _decompile(bin_path, category=category, category_icon=category_icon)
    _write_generated_files(
        decompiled,
        folder / new_project.SETTINGS_DIRNAME,
        SETTINGS_FILENAME,
        SCRIPT_SETTINGS_FILENAME,
        STRINGS_FILENAME,
        map_entries=map_entries,
    )
    _write_generated_files(
        decompiled,
        folder / new_project.BUILD_DIRNAME,
        GENERATED_SETTINGS_FILENAME,
        GENERATED_SCRIPT_SETTINGS_FILENAME,
        GENERATED_STRINGS_FILENAME,
        stats_filename=GENERATED_STATS_FILENAME,
    )


def _write_generated_files(
    decompiled: _Decompiled,
    out_dir: Path,
    settings_filename: str,
    script_settings_filename: str,
    strings_filename: str,
    *,
    stats_filename: str | None = None,
    map_entries: list[maps_io.MapEntry] | None = None,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    settings_io.dump_game_settings(decompiled.game_settings, out_dir / settings_filename)
    settings_io.dump_script_settings(decompiled.script_settings, out_dir / script_settings_filename)
    strings_io.write_strings_json(decompiled.strings, out_dir / strings_filename)
    if stats_filename is not None and decompiled.stats is not None:
        settings_io.dump_build_stats(decompiled.stats, out_dir / stats_filename)
    # None (the build/ snapshot's own call, below) means "not applicable here at all" -- distinct
    # from an empty list (settings/'s own call, when there's genuinely no map scan to filter),
    # which still writes a real (empty) valid_maps.json for consistency with the other three files.
    if map_entries is not None:
        valid_maps = maps_io.filter_maps_for_gametype(list(map_entries), decompiled.script_settings)
        maps_io.write_valid_maps_json(valid_maps, out_dir / maps_io.VALID_MAPS_FILENAME)
