"""Decompiles a source ``.bin`` into a project's ``settings/`` (a live mirror) and ``build/`` (a
disposable ``*.autogenerated.json`` snapshot of the same data), and seeds ``script/output.mgl`` --
the one part of this that a later resync never touches (an RVT-side script edit is pulled into it, with the
user's say-so where that would lose something, by :mod:`in_reach.app.script_sync`'s own caller).

The ``in-reach-v1``/``in-reach-v2`` prototypes did this as part of their own ``init`` command --
see :mod:`in_reach.app.new_project`'s module docstring for why it was left out of this repo's
first pass (the native ``_reachvarianttool`` extension wasn't ported yet). Now that it is (see
:mod:`in_reach.app.rvt.rvt_bridge`), :func:`decompile_into_project` is the thin wrapper that
replaces v1's own ``project_io.write_project_files`` for this repo's folder naming (v1 used
``cfg/``/``dist/``) -- settings/strings/build-stats extracted as validated JSON via
:mod:`in_reach.app.rvt.extraction`/``build_stats``/``settings_io``/``strings_io``, and the Megalo
script itself via the native module's own ``decompile_script()`` (no AST reimplementation needed).

PROMPT.md: "we should have .generated.json files be created when the project is started and they
should update when rvt saves" -- :func:`decompile_into_project` (project creation) writes
``script/output.mgl``, ``settings/`` and the matching ``build/*.autogenerated.json`` snapshot from
the same decompile pass; :func:`resync_from_bin` re-writes just ``settings/``/``build/`` later, on
its own, for ``MainWindow``'s own ``.bin``-file-watcher to call whenever RVT saves over the source
``.bin`` out from under a running project -- ``script/output.mgl`` is deliberately never touched by
that resync itself, since it's the one genuinely hand-editable thing here, not a live mirror of the
``.bin`` the way everything else now is.

Like :mod:`in_reach.app.rvt.compile`, both public entry points here (:func:`decompile_into_project`/
:func:`resync_from_bin`) run their real work (:func:`_decompile_into_project_in_process`/
:func:`_resync_from_bin_in_process`, everything from :func:`~in_reach.app.rvt.rvt_bridge.get_rvt`
onward) in an isolated child process rather than directly in whatever process called them -- see
``compile.py``'s own module docstring for why (the bundled native extension's own Qt5 conflicting
with this app's own PyQt6/Qt6 in the same process). Decompiling happens at every single project
creation, and on every RVT save while a project is open (the ``.bin``-file-watcher's own resync) --
by far the most common way the native extension ever gets loaded into the GUI process at all, so
isolating it here matters at least as much as isolating ``compile.py``'s own less-frequent calls.
"""
from __future__ import annotations

import dataclasses
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from in_reach.app import logging_setup, maps_io, new_project, script_sync
from in_reach.app.categories import EngineCategory, EngineIcon

from . import schema_io, settings_io, strings_io
from .build_stats import build_stats_from_multiplayer
from .extraction import extract_game_settings
from .models.build_stats import BuildStats
from .models.game_settings import GameSettings
from .models.script_settings import ScriptSettings
from .models.strings import StringsDocument
from .rvt_bridge import get_rvt

_logger = logging_setup.get_logger(__name__)

SETTINGS_FILENAME = "settings.json"
SCRIPT_SETTINGS_FILENAME = "script_settings.json"
STRINGS_FILENAME = "strings.json"
SCRIPT_FILENAME = new_project.SCRIPT_FILENAME  # was game.txt, then output.txt (see new_project.migrate_script_file)

GENERATED_SETTINGS_FILENAME = "settings.autogenerated.json"
GENERATED_SCRIPT_SETTINGS_FILENAME = "script_settings.autogenerated.json"
GENERATED_STRINGS_FILENAME = "strings.autogenerated.json"
GENERATED_STATS_FILENAME = "stats.autogenerated.json"

# PROMPT.md: "in settings, please not[e] examples from repo v2 ... where we have a schema, please
# re-add this to the top of the files" -- JSON Schema files for settings/'s own JSON, regenerated
# fresh from the live Pydantic models on every decompile/resync, same as v2's own convention (see
# schema_io.py's docstring). PROMPT.md later: "move settings/schemas into schemas" -- a project-root
# folder of their own (see :data:`~in_reach.app.new_project.SCHEMA_DIRNAME`), not nested under
# settings/, since they document settings/'s JSON shape without being one of its own files. build/'s
# own snapshot doesn't get any -- it's disposable, autogenerated output no editor tooling needs to
# validate against.
SETTINGS_SCHEMA_FILENAME = "settings.schema.json"
SCRIPT_SETTINGS_SCHEMA_FILENAME = "script_settings.schema.json"
STRINGS_SCHEMA_FILENAME = "strings.schema.json"


def normalize_script_text(text: str) -> str:
    """``"\\r\\n"``/``"\\r"`` -> ``"\\n"`` -- applied to a decompiled script before it's ever
    written to ``script/output.mgl`` (see :func:`_decompile_into_project_in_process`'s own comment:
    ``write_text()``'s default text-mode translation would otherwise double each ``"\\r\\n"`` into
    ``"\\r\\r\\n"`` on Windows, PROMPT.md: "when it is generated it is has alternating blanks
    lines"). Public (not module-private) since :mod:`~in_reach.app.rvt.compile` needs the exact same
    normalization to compare a freshly re-``decompile_script()``'d string against that file's own
    on-disk content -- see that module's own "skip recompiling an unchanged script" comment."""
    return text.replace("\r\n", "\n").replace("\r", "\n")


@dataclass
class _Decompiled:
    game_settings: GameSettings
    script_settings: ScriptSettings
    strings: dict
    script_text: str
    stats: BuildStats | None  # only ever present for a multiplayer variant


def _build_decompiled(
    variant,
    source_path: Path,
    *,
    category: EngineCategory,
    category_icon: EngineIcon | None,
    title: str | None = None,
    description: str | None = None,
    created_at: datetime | None = None,
) -> _Decompiled:
    """The shared second half of :func:`_decompile` (loads-then-builds) and
    :func:`write_build_snapshot` (already-loaded/compiled-then-builds) -- everything that turns an
    in-memory ``variant`` into the plain extracted shape :func:`_write_generated_files` writes."""
    game_settings = extract_game_settings(variant, source_path)
    game_settings.meta.category = category
    game_settings.meta.category_icon = category_icon
    # PROMPT.md: "when setting a title and description, this is not being set in settings.json" --
    # at creation time (decompile_into_project) and after a real compile (write_build_snapshot),
    # this project's own title/description (the New Project dialog's, or a hand-edited
    # settings.json's) should override whatever the source .bin's own header carries, same
    # override-with-this-project's-own-value reasoning as category/category_icon above.
    #
    # ``None`` (rather than these two ever defaulting to a blank string) means "no override" --
    # resync_from_bin (RVT saving over the .bin out from under an already-decompiled project) is the
    # one caller that passes neither, specifically so a rename typed straight into RVT's own header
    # field flows through here too (PROMPT.md: "when a project name is changed via rvt ... the
    # project title should change in the tabs and in the breadcrumb"), rather than being silently
    # reverted back to whatever settings.json said before this save. Meta.description has a real,
    # engine-derived max_length (127) shorter than the New Project dialog's own
    # (MAX_DESCRIPTION_LENGTH, 137) -- truncated here rather than raising, since a decompile
    # shouldn't fail over a few characters this field was never going to keep anyway.
    if title is not None:
        game_settings.meta.title = title
    if description is not None:
        game_settings.meta.description = description[:127]
    # PROMPT.md: "every compile was updating this value and causing git changes[;] instead created
    # at and modified at should be set to the same value of when the gametype was created in
    # in-reach" -- extract_game_settings() above always stamps meta.generated_at fresh with
    # datetime.now() (see extraction.py's own _extract_meta()), which is exactly correct exactly
    # once (a project's very first decompile, decompile_into_project -- there's no prior
    # settings.json for that value to have come from yet), and wrong every time after (every later
    # resync_from_bin/write_build_snapshot call, which would otherwise re-stamp it to "now" again on
    # every single compile, a real, confirmed source of pointless VCS-tracked churn -- settings.json
    # changing on every Apply with nothing the user actually edited). Every caller past the first
    # passes this project's own already-established value back in (see
    # settings_io.load_meta_generated_at()) so it only ever gets set once, the same
    # "override-with-this-project's-own-value" pattern as category/category_icon above.
    if created_at is not None:
        game_settings.meta.generated_at = created_at
    script_settings = (
        game_settings.multiplayer.script_settings
        if game_settings.multiplayer is not None
        else ScriptSettings()
    )
    strings = strings_io.extract_strings(variant.multiplayer)
    stats = build_stats_from_multiplayer(variant.multiplayer) if variant.multiplayer is not None else None
    return _Decompiled(game_settings, script_settings, strings, variant.decompile_script(), stats)


def _decompile(
    bin_path: Path,
    *,
    category: EngineCategory,
    category_icon: EngineIcon | None,
    title: str | None = None,
    description: str | None = None,
    created_at: datetime | None = None,
) -> _Decompiled:
    rvt = get_rvt()
    variant = rvt.load(str(bin_path))
    return _build_decompiled(
        variant,
        bin_path,
        category=category,
        category_icon=category_icon,
        title=title,
        description=description,
        created_at=created_at,
    )


def write_build_snapshot(
    variant,
    out_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    title: str | None = None,
    description: str | None = None,
    created_at: datetime | None = None,
) -> None:
    """Extracts from an already-loaded/compiled ``variant`` (see
    :mod:`in_reach.app.rvt.compile`'s ``run_compile()``) and writes *only*
    ``folder``'s ``build/*.autogenerated.json`` snapshot -- never ``settings/``, unlike
    :func:`decompile_into_project`/:func:`resync_from_bin` above. A real compile's own
    ``build/`` snapshot should reflect exactly what the compiler actually produced (echoing
    back its own normalization), not a second re-decompile of ``settings/`` that could silently
    diverge from what got baked into the ``.bin``; hand-edited ``settings/`` stays exactly what
    the user wrote, untouched by a successful Apply.

    Args:
        variant: The just-compiled ``GameVariant`` (already ``.save()``d to ``out_path``).
        out_path: Where ``variant`` was just saved -- used as this snapshot's own
            ``meta.source_file``.
        folder: The gametype project folder whose ``build/`` to write into.
        category/category_icon/title/description: This project's own values, same as
            :func:`decompile_into_project` -- callers should read these back from
            ``settings/settings.json`` (see
            :func:`~in_reach.app.rvt.settings_io.load_meta_category`/``load_meta_title_description``)
            rather than losing them.
        created_at: This project's own ``meta.generated_at``, same reasoning as
            category/category_icon -- callers should read it back via
            :func:`~in_reach.app.rvt.settings_io.load_meta_generated_at` so a real compile doesn't
            re-stamp it to ``datetime.now()`` (see :meth:`_build_decompiled`'s own comment on why).
    """
    decompiled = _build_decompiled(
        variant,
        out_path,
        category=category,
        category_icon=category_icon,
        title=title,
        description=description,
        created_at=created_at,
    )
    _write_generated_files(
        decompiled,
        folder / new_project.BUILD_DIRNAME,
        GENERATED_SETTINGS_FILENAME,
        GENERATED_SCRIPT_SETTINGS_FILENAME,
        GENERATED_STRINGS_FILENAME,
        stats_filename=GENERATED_STATS_FILENAME,
    )
    # The script this .bin holds, and which output.mgl it was built from -- what lets a later RVT save
    # be recognised as having changed the script (see script_sync's own docstring).
    script_sync.record_build(folder, normalize_script_text(decompiled.script_text))


def _serialize_decompile_request(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory,
    category_icon: EngineIcon | None,
    title: str | None,
    description: str | None,
    created_at: datetime | None,
    map_entries: list[maps_io.MapEntry],
) -> dict:
    """Everything :func:`_run_decompile_isolated` needs the child process to reconstruct before
    calling the real ``_in_process`` function -- plain JSON-safe types only (see
    :mod:`in_reach.app.rvt.decompile_subprocess`'s own deserialization, the exact inverse)."""
    return {
        "bin_path": str(bin_path),
        "folder": str(folder),
        "category": int(category),
        "category_icon": int(category_icon) if category_icon is not None else None,
        "title": title,
        "description": description,
        "created_at": created_at.isoformat() if created_at is not None else None,
        "map_entries": [dataclasses.asdict(entry) for entry in map_entries],
    }


def _run_decompile_isolated(
    mode: str,
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory,
    category_icon: EngineIcon | None,
    title: str | None,
    description: str | None,
    created_at: datetime | None,
    map_entries: list[maps_io.MapEntry],
) -> None:
    """Runs ``mode`` (``"into_project"`` or ``"resync"``) in a fresh, isolated ``python -m`` child
    process -- see this module's own docstring for why. Shared by :func:`decompile_into_project`/
    :func:`resync_from_bin`, whose real (``_in_process``) implementations differ only in which
    generated files they write, not in how they need isolating.

    Raises:
        RuntimeError: The child process reported a failure, or crashed outright (e.g. the same
            native access violation this isolation exists to contain) -- wrapping whatever the
            child's own exception message was, or its exit code if it never got the chance to
            report one at all. Never the *original* exception type/traceback -- those can't cross
            a process boundary -- but every real caller here only ever needed the message anyway
            (see e.g. :func:`~in_reach.app.new_project._decompile_source_variant`'s own
            ``except Exception as exc: f"...: {exc}"``).
    """
    request = _serialize_decompile_request(
        bin_path,
        folder,
        category=category,
        category_icon=category_icon,
        title=title,
        description=description,
        created_at=created_at,
        map_entries=map_entries,
    )
    request_fd, request_path_str = tempfile.mkstemp(prefix="in-reach-decompile-req-", suffix=".json")
    result_fd, result_path_str = tempfile.mkstemp(prefix="in-reach-decompile-res-", suffix=".json")
    os.close(result_fd)
    request_path = Path(request_path_str)
    result_path = Path(result_path_str)
    try:
        with os.fdopen(request_fd, "w", encoding="utf-8") as handle:
            json.dump(request, handle)

        proc = subprocess.run(
            [sys.executable, "-m", "in_reach.app.rvt.decompile_subprocess", mode, str(request_path), str(result_path)],
            capture_output=True,
            text=True,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
        if proc.returncode != 0:
            _logger.error(
                "decompile subprocess (%s) for %s exited with code %s: %s",
                mode,
                folder,
                proc.returncode,
                (proc.stderr or proc.stdout).strip(),
            )
            raise RuntimeError(
                f"The decompile process exited unexpectedly (code {proc.returncode})."
                f"{(' ' + proc.stderr.strip()) if proc.stderr.strip() else ''}"
            )
        try:
            outcome = json.loads(result_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            _logger.exception("couldn't read decompile subprocess result for %s", folder)
            raise RuntimeError(f"Couldn't read the decompile result: {exc}") from exc
        if not outcome.get("success"):
            raise RuntimeError(outcome.get("error") or "Decompile failed for an unknown reason.")
    finally:
        request_path.unlink(missing_ok=True)
        result_path.unlink(missing_ok=True)


def decompile_into_project(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    title: str | None = None,
    description: str | None = None,
    created_at: datetime | None = None,
    map_entries: list[maps_io.MapEntry] = (),
) -> None:
    """Isolated-child-process wrapper around :func:`_decompile_into_project_in_process` -- see this
    module's own docstring for why, and that function's own docstring for what this actually does
    and its arguments/raises."""
    _run_decompile_isolated(
        "into_project",
        bin_path,
        folder,
        category=category,
        category_icon=category_icon,
        title=title,
        description=description,
        created_at=created_at,
        map_entries=list(map_entries),
    )


def resync_from_bin(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    title: str | None = None,
    description: str | None = None,
    created_at: datetime | None = None,
    map_entries: list[maps_io.MapEntry] = (),
) -> None:
    """Isolated-child-process wrapper around :func:`_resync_from_bin_in_process` -- see this
    module's own docstring for why, and that function's own docstring for what this actually does
    and its arguments/raises."""
    _run_decompile_isolated(
        "resync",
        bin_path,
        folder,
        category=category,
        category_icon=category_icon,
        title=title,
        description=description,
        created_at=created_at,
        map_entries=list(map_entries),
    )


def _with_engine_category(decompiled: _Decompiled, category: EngineCategory, category_icon: EngineIcon | None) -> _Decompiled:
    """``decompiled`` with the project's chosen category (and its icon) also in
    ``multiplayer.game_settings.metadata.engine_category``/``categorization_icon`` -- the fields a build writes into the
    variant, and so what the game shows. ``meta.category`` alone is only this project's own label.

    Only for ``settings/`` at creation: the ``build/`` snapshot keeps what the source ``.bin`` really holds, so the
    difference is a change the first build applies. ``none`` ("Forge / None", the New Project dialog's default) leaves
    the source's own category and icon alone, so a personal variant keeps its category unless another one is chosen.
    """
    from in_reach.app.rvt.models import enums

    settings = decompiled.game_settings
    if category == EngineCategory.none or settings.multiplayer is None:
        return decompiled
    changed = settings.model_copy(deep=True)
    metadata = changed.multiplayer.game_settings.metadata
    metadata.engine_category = enums.EngineCategory(int(category))
    if category_icon is not None:
        metadata.categorization_icon = enums.EngineIcon(int(category_icon))
    return dataclasses.replace(decompiled, game_settings=changed)


def _decompile_into_project_in_process(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    title: str | None = None,
    description: str | None = None,
    created_at: datetime | None = None,
    map_entries: list[maps_io.MapEntry] = (),
) -> None:
    """Loads ``bin_path`` through the bundled ReachVariantTool extension and writes what it decodes
    into ``folder``'s ``settings/`` (settings/script settings/strings/valid maps, as JSON) and
    ``edit/rvt/`` (the decompiled Megalo script, as plain text) -- plus, per PROMPT.md, the matching
    ``build/*.autogenerated.json`` snapshot (see :func:`_write_generated_files`), so a
    freshly-created project already has both halves rather than an empty ``build/`` until the next
    RVT save.

    Args:
        bin_path: The source ``.bin`` to decompile -- normally
            :func:`~in_reach.app.new_project.source_variant_path`'s result for ``folder``.
        folder: The gametype project folder to write into, as returned by
            :func:`~in_reach.app.new_project.create_gametype_project`.
        category: This project's own :class:`~in_reach.app.categories.EngineCategory` (PROMPT.md:
            "move category and category_icon into settings.json") -- independent of whatever the
            source ``.bin`` itself carries as its engine-level category (see
            ``Meta.category``'s own docstring).
        category_icon: This project's own :class:`~in_reach.app.categories.EngineIcon`.
        title: This project's own title (PROMPT.md: "when setting a title and description, this
            is not being set in settings.json") -- stamped into ``meta.title``, overriding whatever
            title the source ``.bin`` itself carries in its own header.
        description: This project's own description, stamped into ``meta.description`` the same
            way (truncated to fit that field's own, shorter, engine-derived length limit).
        created_at: Left ``None`` by this function's own real caller (project creation, which has
            no prior ``settings/settings.json`` for a value to have come from yet) -- see
            :func:`_build_decompiled`'s own comment for why ``None`` is exactly correct here (the
            freshly-extracted ``datetime.now()`` becomes this project's own permanent "created in
            in-reach" timestamp) and wrong for every later resync/compile.
        map_entries: The shared ``.in-reach/maps.json`` scan (see
            :func:`~in_reach.app.maps_io.scan_maps`), narrowed down into ``settings/valid_maps.json``
            via :func:`~in_reach.app.maps_io.filter_maps_for_gametype`.

    Raises:
        Whatever the native extension or pydantic validation raises for a ``.bin`` it can't load or
        make sense of -- callers decide whether that should block project creation or just surface
        as a warning (see that function's own handling).

    Only ever called from :mod:`in_reach.app.rvt.decompile_subprocess`, inside the isolated child
    process the public :func:`decompile_into_project` spawns -- never call this directly from the
    GUI process, see this module's own docstring for why.
    """
    decompiled = _decompile(
        bin_path,
        category=category,
        category_icon=category_icon,
        title=title,
        description=description,
        created_at=created_at,
    )

    script_dir = folder / new_project.SCRIPT_DIRNAME
    script_dir.mkdir(parents=True, exist_ok=True)
    # decompile_script() itself already returns "\r\n"-terminated lines -- write_text()'s own
    # default text-mode translation (any "\n" -> os.linesep) would then double each one to
    # "\r\r\n" on Windows, which reads back as two lines (a blank line after every real one, see
    # PROMPT.md: "when it is generated it is has alternating blanks lines"). Normalizing to a bare
    # "\n" first sidesteps that double-translation regardless of platform.
    script_text = normalize_script_text(decompiled.script_text)
    (script_dir / SCRIPT_FILENAME).write_text(script_text, encoding="utf-8")

    _write_generated_files(
        _with_engine_category(decompiled, category, category_icon),
        folder / new_project.SETTINGS_DIRNAME,
        SETTINGS_FILENAME,
        SCRIPT_SETTINGS_FILENAME,
        STRINGS_FILENAME,
        write_schema=True,
        folder=folder,
    )
    _write_generated_files(
        decompiled,
        folder / new_project.BUILD_DIRNAME,
        GENERATED_SETTINGS_FILENAME,
        GENERATED_SCRIPT_SETTINGS_FILENAME,
        GENERATED_STRINGS_FILENAME,
        stats_filename=GENERATED_STATS_FILENAME,
        # PROMPT.md: "move settings/valid_maps.json to build/valid_maps.json".
        map_entries=map_entries,
    )
    script_sync.record_build(folder, script_text)


def _resync_from_bin_in_process(
    bin_path: Path,
    folder: Path,
    *,
    category: EngineCategory = EngineCategory.none,
    category_icon: EngineIcon | None = None,
    title: str | None = None,
    description: str | None = None,
    created_at: datetime | None = None,
    map_entries: list[maps_io.MapEntry] = (),
) -> None:
    """Re-decompiles ``bin_path`` and rewrites ``folder``'s ``settings/`` and
    ``build/*.autogenerated.json`` snapshot -- PROMPT.md: "[generated files] should update when
    rvt saves". ``script/output.mgl`` is left completely alone: this is meant to be called
    whenever the *source* ``.bin`` changes out from under an already-decompiled project (RVT saving
    over it), not at project creation, and that script is the one genuinely hand-editable thing
    here, never auto-overwritten by this function. What the ``.bin``'s script now says is recorded in
    ``build/script.autogenerated.json`` (see :mod:`in_reach.app.script_sync`) so the *caller* can tell
    that RVT changed it and decide -- asking the user if need be -- whether to pull it into
    ``output.mgl``; the IDE's file watcher does (``MainWindow._pull_script_from_rvt``).

    Args:
        bin_path: The ``.bin`` that just changed.
        folder: The gametype project folder to resync.
        category/category_icon: This project's own classification, same as
            :func:`decompile_into_project` -- callers should read these back from the project's
            existing ``settings/settings.json`` (see
            :func:`~in_reach.app.rvt.settings_io.load_meta_category`) rather than losing them on
            every resync -- unlike title/description below, a project's category isn't something
            the ``.bin`` itself has any concept of at all, so there's nothing for a resync to ever
            pick up *from* it.
        title/description: Left ``None`` by every real caller (the ``.bin``-file-watcher) on
            purpose -- PROMPT.md: "when a project name is changed via rvt ... the project title
            should change in the tabs and in the breadcrumb". Passing an explicit override here
            would silently revert a rename typed straight into RVT's own header field back to
            whatever ``settings.json`` said before this save; leaving both ``None`` instead lets
            the freshly-extracted values from ``bin_path`` itself flow straight into
            ``settings/settings.json`` (and, from there, into the project's README -- see
            :func:`~in_reach.app.new_project.set_project_title` -- and every UI that reads
            :func:`~in_reach.app.new_project.read_project_title`). Still accepted as real overrides
            for anything that *does* want one (see ``test_resync_from_bin_carries_title_and_
            description_through``).
        created_at: Same reasoning as category/category_icon above, NOT title/description -- a
            project's own "created in in-reach" moment isn't something RVT has any concept of
            either, so every real caller should read this back via
            :func:`~in_reach.app.rvt.settings_io.load_meta_generated_at` rather than letting it
            re-stamp to ``datetime.now()`` on every resync (see :func:`_build_decompiled`'s own
            comment for why that would otherwise be a real, git-tracked-churn bug).
        map_entries: Same as :func:`decompile_into_project` -- callers should read this back from
            ``.in-reach/maps.json`` (see :func:`~in_reach.app.maps_io.read_maps_json`) rather than
            re-scanning the map-variant folders on every resync.

    Raises:
        Same as :func:`decompile_into_project` -- callers watching for RVT saves should treat this
        as best-effort and not let it crash the whole app over a ``.bin`` RVT left mid-write.

    Only ever called from :mod:`in_reach.app.rvt.decompile_subprocess`, inside the isolated child
    process the public :func:`resync_from_bin` spawns -- never call this directly from the GUI
    process, see this module's own docstring for why.
    """
    decompiled = _decompile(
        bin_path,
        category=category,
        category_icon=category_icon,
        title=title,
        description=description,
        created_at=created_at,
    )
    _write_generated_files(
        decompiled,
        folder / new_project.SETTINGS_DIRNAME,
        SETTINGS_FILENAME,
        SCRIPT_SETTINGS_FILENAME,
        STRINGS_FILENAME,
        write_schema=True,
        folder=folder,
    )
    _write_generated_files(
        decompiled,
        folder / new_project.BUILD_DIRNAME,
        GENERATED_SETTINGS_FILENAME,
        GENERATED_SCRIPT_SETTINGS_FILENAME,
        GENERATED_STRINGS_FILENAME,
        stats_filename=GENERATED_STATS_FILENAME,
        map_entries=map_entries,
    )
    # Records what the .bin's script now says, but leaves output.mgl alone: whether RVT's version should
    # replace it is a decision for the caller (see script_sync.plan_pull), who can ask the user.
    script_sync.record_sync(folder, normalize_script_text(decompiled.script_text))


def _write_generated_files(
    decompiled: _Decompiled,
    out_dir: Path,
    settings_filename: str,
    script_settings_filename: str,
    strings_filename: str,
    *,
    stats_filename: str | None = None,
    map_entries: list[maps_io.MapEntry] | None = None,
    write_schema: bool = False,
    folder: Path | None = None,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    settings_schema_path = script_settings_schema_path = strings_schema_path = None
    if write_schema:
        # PROMPT.md: "move settings/schemas into schemas" -- a project-root schemas/ (folder, not
        # out_dir -- the caller passing write_schema=True is always settings/'s own call, but the
        # schema files themselves no longer live inside settings/ at all).
        schema_dir = folder / new_project.SCHEMA_DIRNAME
        settings_schema_path = schema_io.dump_json_schema(GameSettings, schema_dir / SETTINGS_SCHEMA_FILENAME)
        script_settings_schema_path = schema_io.dump_json_schema(
            ScriptSettings, schema_dir / SCRIPT_SETTINGS_SCHEMA_FILENAME
        )
        strings_schema_path = schema_io.dump_json_schema(StringsDocument, schema_dir / STRINGS_SCHEMA_FILENAME)

    settings_io.dump_game_settings(decompiled.game_settings, out_dir / settings_filename, settings_schema_path)
    # PROMPT.md: "in script_setting.json please remove [the] '_comment'" (see git history) -- entries
    # in forge_labels are protected directly in the editor instead (PROMPT.md: "entries in forge
    # labels ... should instead not be changeable"), see editor.py's own forge-label-name protection.
    settings_io.dump_script_settings(
        decompiled.script_settings, out_dir / script_settings_filename, script_settings_schema_path
    )
    strings_io.write_strings_json(decompiled.strings, out_dir / strings_filename, strings_schema_path)
    if stats_filename is not None and decompiled.stats is not None:
        settings_io.dump_build_stats(decompiled.stats, out_dir / stats_filename)
    # None (settings/'s own call, above) means "not applicable here at all" -- PROMPT.md: "move
    # settings/valid_maps.json to build/valid_maps.json", so only build/'s own call ever passes
    # this now. Distinct from an empty list (a genuinely empty map scan), which still writes a real
    # (empty) valid_maps.json for consistency with the other three files.
    if map_entries is not None:
        valid_maps = maps_io.filter_maps_for_gametype(list(map_entries), decompiled.script_settings)
        maps_io.write_valid_maps_json(valid_maps, out_dir / maps_io.VALID_MAPS_FILENAME)
